// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { anyApi } from "lunorash/server/types";
import type { FunctionReference } from "lunorash/client";

export interface ApiTypes {}

export const api = anyApi as unknown as ApiTypes;

/** Internal functions — callable only server-side via `ctx.run*`, never from a client. */
export interface InternalApiTypes {}

export const internal = anyApi as unknown as InternalApiTypes;
