// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { anyApi } from "lunorash/client";
import type { FunctionReference } from "lunorash/client";

export interface ApiTypes {
    mutators: {
        appendChild: FunctionReference<"mutation", { id: string; userId: string; parentId: string; text: string; isTask?: boolean; kind?: "paragraph"; createdAt: number; updatedAt: number }, { id: string; }>;
        applyChangeOps: FunctionReference<"mutation", { userId: string; ops: Array<{ op: "insert"; value: { id: string; parentId: string; prevSiblingId: string; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number; mirrorOf: string; createdAt: number; updatedAt: number; origin: string; kind: "paragraph" } } | { op: "update"; value: { id: string; parentId: string; prevSiblingId: string; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number; mirrorOf: string; createdAt: number; updatedAt: number; origin: string; kind: "paragraph" } } | { op: "delete"; key: string }> }, { count: number; deletes: number; inserts: number; patches: number; }>;
        claimDailyMapping: FunctionReference<"mutation", { userId: string; key: string; nodeId: string; touchedAt: number }, { nodeId: string; won: boolean; }>;
        deleteDailyMapping: FunctionReference<"mutation", { userId: string; key: string }, void>;
        deleteSavedQuery: FunctionReference<"mutation", { userId: string; id: string }, void>;
        deleteTagColor: FunctionReference<"mutation", { userId: string; tag: string }, void>;
        getMigrateState: FunctionReference<"mutation", { userId: string }, { nodesAt: number | null; kvAt: number | null; }>;
        hello: FunctionReference<"mutation", { userId: string }, { ok: true; userId: string; }>;
        importKvRows: FunctionReference<"mutation", { userId: string; rows: Array<{ kind: "tagColor"; tag: string; color: string } | { kind: "savedQuery"; id: string; name: string; query: string; createdAt: number } | { kind: "dailyIndex"; key: string; nodeId: string; touchedAt: number }> }, { count: number; }>;
        importNodes: FunctionReference<"mutation", { userId: string; nodes: Array<{ id: string; userId: string; parentId: string; prevSiblingId: string; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number; mirrorOf: string; createdAt: number; updatedAt: number; origin: string; kind: "paragraph" }> }, { count: number; inserted: number; patched: number; }>;
        indent: FunctionReference<"mutation", { id: string; userId: string; updatedAt: number; resolveMirror?: boolean }, void>;
        indentMany: FunctionReference<"mutation", { userId: string; nodeIds: Array<string>; updatedAt: number; resolveMirror?: boolean }, void>;
        insertChildAtStart: FunctionReference<"mutation", { id: string; userId: string; parentId: string; text: string; isTask?: boolean; kind?: "paragraph"; createdAt: number; updatedAt: number }, { id: string; }>;
        insertSibling: FunctionReference<"mutation", { id: string; userId: string; parentId: string; afterId: string; text: string; isTask?: boolean; kind?: "paragraph"; createdAt: number; updatedAt: number }, { id: string; }>;
        materializeDailyNodes: FunctionReference<"mutation", { userId: string; inserts: Array<{ id: string; parentId: string; afterId: string; text: string }>; createdAt: number; updatedAt: number }, { count: number; }>;
        mirrorNode: FunctionReference<"mutation", { id: string; userId: string; sourceId: string; targetParentId: string; createdAt: number; updatedAt: number }, { id: string; }>;
        moveMany: FunctionReference<"mutation", { userId: string; targetId: string; nodeIds: Array<string>; updatedAt: number }, void>;
        moveNode: FunctionReference<"mutation", { id: string; userId: string; newParentId: string; afterSiblingId: string; updatedAt: number; expandIds?: Array<string> }, void>;
        outdent: FunctionReference<"mutation", { id: string; userId: string; updatedAt: number }, void>;
        outdentMany: FunctionReference<"mutation", { userId: string; nodeIds: Array<string>; updatedAt: number }, void>;
        patchSavedQuery: FunctionReference<"mutation", { userId: string; id: string; name?: string; query?: string }, void>;
        removeMany: FunctionReference<"mutation", { userId: string; nodeIds: Array<string>; updatedAt: number }, void>;
        removeNode: FunctionReference<"mutation", { id: string; userId: string; updatedAt: number }, void>;
        restoreNodes: FunctionReference<"mutation", { userId: string; nodes: Array<{ id: string; userId: string; parentId: string; prevSiblingId: string; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number; mirrorOf: string; createdAt: number; updatedAt: number; origin: string; kind: "paragraph" }> }, { deletes: number; inserts: number; patches: number; }>;
        seedIfEmpty: FunctionReference<"mutation", { userId: string; createdAt: number }, { seeded: false; ids?: undefined; } | { seeded: true; ids: string[]; }>;
        setBookmarkedAt: FunctionReference<"mutation", { id: string; userId: string; bookmarkedAt: number; updatedAt: number }, void>;
        setCollapsed: FunctionReference<"mutation", { id: string; userId: string; collapsed: boolean; updatedAt: number }, void>;
        setCompleted: FunctionReference<"mutation", { id: string; userId: string; completed: boolean; updatedAt: number }, void>;
        setIsTask: FunctionReference<"mutation", { id: string; userId: string; isTask: boolean; updatedAt: number }, void>;
        setKind: FunctionReference<"mutation", { id: string; userId: string; kind: "paragraph"; updatedAt: number }, void>;
        setMigrateState: FunctionReference<"mutation", { userId: string; nodesAt?: number; kvAt?: number }, { nodesAt: number | null; kvAt: number | null; }>;
        setText: FunctionReference<"mutation", { id: string; userId: string; text: string; updatedAt: number }, void>;
        splitNode: FunctionReference<"mutation", { id: string; newId: string; userId: string; parentId: string; afterId: string; leftText: string; rightText: string; isTask?: boolean; kind?: "paragraph"; createdAt: number; updatedAt: number }, { id: string; }>;
        upsertDailyMapping: FunctionReference<"mutation", { userId: string; key: string; nodeId: string; touchedAt: number }, void>;
        upsertSavedQuery: FunctionReference<"mutation", { userId: string; id: string; name: string; query: string; createdAt: number }, void>;
        upsertTagColor: FunctionReference<"mutation", { userId: string; tag: string; color: string }, void>;
    };
}

export const api = anyApi as unknown as ApiTypes;

/** Internal functions — callable only server-side via `ctx.run*`, never from a client. */
export interface InternalApiTypes {
    mcp: {
        applyChangeOps: FunctionReference<"mutation", { userId: string; ops: Array<{ op: "insert"; value: { id: string; parentId: string; prevSiblingId: string; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number; mirrorOf: string; createdAt: number; updatedAt: number; origin: string; kind: "paragraph" } } | { op: "update"; value: { id: string; parentId: string; prevSiblingId: string; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number; mirrorOf: string; createdAt: number; updatedAt: number; origin: string; kind: "paragraph" } } | { op: "delete"; key: string }> }, { count: number; deletes: number; inserts: number; patches: number; }>;
        claimDailyMapping: FunctionReference<"mutation", { userId: string; key: string; nodeId: string; touchedAt: number }, { nodeId: string; won: boolean; }>;
        freezeAndExportRetirement: FunctionReference<"mutation", { userId: string; migrationId: string; now: number }, { version: number; exportedAt: number; userId: string; nodes: { userId: string; id: string; parentId: string | null; prevSiblingId: string | null; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number | null; mirrorOf: string | null; createdAt: number; updatedAt: number; origin: string | null; kind: "paragraph" | null; }[]; dailyIndex: { key: string; nodeId: string; touchedAt: number; userId: string; }[]; tagColors: { tag: string; color: string; userId: string; }[]; savedQueries: { id: string; name: string; query: string; createdAt: number; userId: string; }[]; migrateState: { nodesAt: number | null; kvAt: number | null; userId: string; }[]; }>;
        inspectRetirement: FunctionReference<"query", { userId: string }, { retirement: { migrationId: string; status: string; updatedAt: number; } | null; snapshot: { version: number; exportedAt: number; userId: string; nodes: { userId: string; id: string; parentId: string | null; prevSiblingId: string | null; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number | null; mirrorOf: string | null; createdAt: number; updatedAt: number; origin: string | null; kind: "paragraph" | null; }[]; dailyIndex: { key: string; nodeId: string; touchedAt: number; userId: string; }[]; tagColors: { tag: string; color: string; userId: string; }[]; savedQueries: { id: string; name: string; query: string; createdAt: number; userId: string; }[]; migrateState: { nodesAt: number | null; kvAt: number | null; userId: string; }[]; }; }>;
        listDailyIndex: FunctionReference<"query", { userId: string }, { key: string; nodeId: string; }[]>;
        listNodes: FunctionReference<"query", { userId: string }, { id: string; parentId: string | null; prevSiblingId: string | null; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number | null; mirrorOf: string | null; createdAt: number; updatedAt: number; origin: string | null; kind: "paragraph" | null }[]>;
        markRetirementVerified: FunctionReference<"mutation", { userId: string; migrationId: string; now: number }, { retired: boolean; }>;
        releaseRetirementFreeze: FunctionReference<"mutation", { userId: string; migrationId: string }, { released: boolean; }>;
        wipeUserShard: FunctionReference<"mutation", { userId: string }, { deleted: number; tables: Record<string, number>; }>;
    };
}

export const internal = anyApi as unknown as InternalApiTypes;
