// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { anyApi } from "lunorash/server/types";
import type { FunctionReference } from "lunorash/client";

export interface ApiTypes {}

export const api = anyApi as unknown as ApiTypes;

/** Internal functions — callable only server-side via `ctx.run*`, never from a client. */
export interface InternalApiTypes {
    mcp: {
        applyChangeOps: FunctionReference<"mutation", { userId: string; ops: Array<unknown> }, { count: number; deletes?: undefined; inserts?: undefined; patches?: undefined; } | { count: number; deletes: number; inserts: number; patches: number; }>;
        listDailyIndex: FunctionReference<"query", { userId: string }, { key: string; nodeId: string; }[]>;
        listNodes: FunctionReference<"query", { userId: string }, { id: string; parentId: string | null; prevSiblingId: string | null; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number | null; mirrorOf: string | null; createdAt: number; updatedAt: number; origin: string | null; kind: "paragraph" | null }[]>;
    };
}

export const internal = anyApi as unknown as InternalApiTypes;
