// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { ExecutionContextLike, LunoraWorker, Route, ScheduledControllerLike, ShardNamespaceLike, WorkerOptions } from "lunorash/runtime";
import { createWorker, resolveLogArchiveFromEnv } from "lunorash/runtime";

import { LUNORA_CRONS } from "./crons.js";
import { LUNORA_FUNCTIONS } from "./functions.js";
import { openApiSpec } from "./openapi.js";
import { createShardDO } from "./shard.js";

/** Read a value off the per-request `env`. Returns `undefined` to leave the capability unconfigured (its `ctx.*`/admin surface stays a clear-error stub). */
type Selector<Env, T> = (env: Env) => T | undefined;

/** The composed app: a Cloudflare module worker (`fetch` / `scheduled` / optional `email`) plus the `ShardDO` class binding. */
interface ComposedApp extends LunoraWorker {
    /** Cloudflare Email Routing entry — present only when `.onEmail(...)` was configured. */
    email?: (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>;
    /** The generated shard Durable Object class — re-export it as a named export so wrangler can bind it. */
    ShardDO: ReturnType<typeof createShardDO>;
}

/**
 * Fluent worker-composition builder. Records each capability declaration, then
 * `.build()` fans them into the DO-side `createShardDO` factory and the
 * worker-side `createWorker` options — constructing the worker lazily on the
 * first request so per-isolate singletons are built once.
 */
class AppBuilder<Env extends Record<string, unknown>> {
    private adminToken?: Selector<Env, string>;
    private readonly extendFns: ((env: Env, derived: Readonly<WorkerOptions>) => Partial<WorkerOptions>)[] = [];
    private readonly routeMap: Record<string, Route> = {};
    private shardSelector?: Selector<Env, ShardNamespaceLike>;

    private emailHandler?: (env: Env) => (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>;

    /** Bearer token gating the `/_lunora/admin/*` endpoints the studio calls. */
    public admin(selector: Selector<Env, string>): this {
        this.adminToken = selector;

        return this;
    }

    /** Escape hatch — merge raw `WorkerOptions` (anything not yet sugared) over the derived options at build time. The second `derived` argument is a snapshot of the options assembled so far (after `.auth(...)` etc.), so you can compose rather than clobber — e.g. wrap `derived.resolveIdentity` instead of replacing it. */
    public extend(fn: (env: Env, derived: Readonly<WorkerOptions>) => Partial<WorkerOptions>): this {
        this.extendFns.push(fn);

        return this;
    }

    /** Cloudflare Email Routing entry — exposes the top-level `email` handler. */
    public onEmail(handler: (env: Env) => (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>): this {
        this.emailHandler = handler;

        return this;
    }

    /** Mount a custom HTTP route (e.g. an asset-serving or test endpoint). Key is `"METHOD path"`, `"path"`, or a path prefix matched by the runtime. */
    public route(key: string, handler: Route): this {
        this.routeMap[key] = handler;

        return this;
    }

    /** The shard Durable Object namespace (typically `env.SHARD`) — required: every app routes RPC + WebSocket traffic through it. */
    public shard(selector: Selector<Env, ShardNamespaceLike>): this {
        this.shardSelector = selector;

        return this;
    }

    /** Materialise the standalone Cloudflare worker + `ShardDO` class. */
    public build(): ComposedApp {
        return this.assemble();
    }

    /** Build the shard DO + compose the worker (standalone or framework-hosted), wrapping the lazy per-isolate singletons + auth init. */
    private assemble(): ComposedApp {
        const ShardDO = createShardDO({});

        // Per-isolate singletons: the worker (and auth instance) are expensive to
        // build, so the first request constructs them and every later request on
        // the same isolate reuses them.
        let worker: LunoraWorker | null = null;

        const buildWorker = (env: Env): LunoraWorker => createWorker(this.buildWorkerOptions(env, () => null));

        const composed: ComposedApp = {
            ShardDO,
            fetch: async (request: Request, rawEnv: unknown, context: ExecutionContextLike): Promise<Response> => {
                const env = rawEnv as Env;
                worker ??= buildWorker(env);

                return worker.fetch(request, rawEnv, context);
            },
            scheduled: async (controller: ScheduledControllerLike, rawEnv: unknown, context: ExecutionContextLike): Promise<void> => {
                worker ??= buildWorker(rawEnv as Env);

                return worker.scheduled(controller, rawEnv, context);
            },
            serverQuery: (request, rawEnv, reference, args, options) => {
                worker ??= buildWorker(rawEnv as Env);

                return worker.serverQuery(request, rawEnv, reference, args, options);
            },
        };

        if (this.emailHandler) {
            const handler = this.emailHandler;

            composed.email = (message, rawEnv, context) => handler(rawEnv as Env)(message, rawEnv, context);
        }

        return composed;
    }

    /** Fan the recorded declarations into the worker-side `createWorker` options. */
    private buildWorkerOptions(env: Env, _getAuth: () => null): WorkerOptions {
        const options: WorkerOptions = {
            cronJobs: LUNORA_CRONS,
            functions: LUNORA_FUNCTIONS,
            openApiSpec,
            routes: this.routeMap,
            shardDO: this.shardSelector?.(env) ?? (undefined as unknown as ShardNamespaceLike),
        };

        if (this.adminToken) {
            options.adminToken = this.adminToken(env);
        }

        options.logArchive = resolveLogArchiveFromEnv(env);

        for (const fn of this.extendFns) {
            Object.assign(options, fn(env, { ...options }));
        }

        return options;
    }
}

/** Start composing the app. Chain the capability methods, then `.build()`. */
const defineApp = <Env extends Record<string, unknown>>(): AppBuilder<Env> => new AppBuilder<Env>();

export { AppBuilder, defineApp };
export type { ComposedApp, Selector };
