// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { ExecutionContextLike, HttpRouterLike, LunoraWorker, Route, ScheduledControllerLike, ShardNamespaceLike, WorkerOptions } from "lunorash/runtime";
import { createWorker, resolveLogArchiveFromEnv } from "lunorash/runtime";

import { LUNORA_CRONS } from "./crons.js";
import { LUNORA_FUNCTIONS } from "./functions.js";
import { openApiSpec } from "./openapi.js";
import { createShardDO } from "./shard.js";

/** Read a value off the per-request `env`. Returns `undefined` to leave the capability unconfigured (its `ctx.*`/admin surface stays a clear-error stub). */
type Selector<Env, T> = (env: Env) => T | undefined;

/** The generated `createShardDO` config — `.observability()`, `.maxRelationKeys()` and the long-tail `.ai()` / `.kv()` / … methods pass straight through to it. */
type ShardConfig = NonNullable<Parameters<typeof createShardDO>[0]>;

/** The composed app: a Cloudflare module worker (`fetch` / `scheduled` / optional `email`) plus the `ShardDO` class binding. */
interface ComposedApp extends LunoraWorker {
    /** Cloudflare Email Routing entry — present only when `.onEmail(...)` was configured. */
    email?: (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>;
    /** The generated shard Durable Object class — re-export it as a named export so wrangler can bind it. */
    ShardDO: ReturnType<typeof createShardDO>;
}

/**
 * Fluent worker-composition builder. Records each capability declaration, then
 * `.build()` fans them into the DO-side `createShardDO` factory and the
 * worker-side `createWorker` options — constructing the worker lazily on the
 * first request so per-isolate singletons are built once.
 */
class AppBuilder<Env extends object> {
    private adminToken?: Selector<Env, string>;
    private cdcEnabled = false;
    private reactiveCacheConfig: boolean | { maxBytes?: number; maxEntries?: number } = false;
    private maxRelationKeysLimit?: ShardConfig["maxRelationKeys"];
    private observabilitySink?: ShardConfig["observability"];
    private relationExistsPushDownMode?: ShardConfig["relationExistsPushDown"];
    private readonly extendFns: ((env: Env, derived: Readonly<WorkerOptions>) => Partial<WorkerOptions>)[] = [];
    private httpRouterApp?: HttpRouterLike;
    private readonly routeMap: Record<string, Route> = {};
    private shardSelector?: Selector<Env, ShardNamespaceLike>;

    private emailHandler?: (env: Env) => (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>;

    /** Bearer token gating the `/_lunora/admin/*` endpoints the studio calls. */
    public admin(selector: Selector<Env, string>): this {
        this.adminToken = selector;

        return this;
    }

    /**
     * Opt into change-data-capture: every write records a post-image to `__cdc_log` — on this shard AND, when the app has `.global()` tables, on the global backend. Backs streaming export, replay-PITR, and the `.global()` half of `defineShape` replication (whose poll tick asks the global changelog which tables moved). Off by default: it costs a changelog row per write, which an app using none of the above should not pay.
     *
     * REQUIRED for a shard-local `defineShape`: those replicate out of `__cdc_log`, and a `shape_subscribe` is refused with `SHAPE_REQUIRES_CDC` without it.
     *
     * It also changes how fresh a `.global()` shape is against writes made OUTSIDE `ctx.db` — an admin import, a PITR replay, an external ETL job, or a predicate over wall clock. With CDC off the poll re-reads every shape every 2s. With it on the poll asks the global changelog which tables moved and skips the rest, so a change the changelog never saw waits for the 30s unconditional resync instead. Writes through `ctx.db` are unaffected: they append, so the poll sees them on the next tick either way.
     */
    public cdc(enabled = true): this {
        this.cdcEnabled = enabled;

        return this;
    }

    /**
     * Enable the per-shard reactive query cache: query results are memoized by `(functionPath, args, identity)` and invalidated by the ctx-db write hooks BEFORE the subscription broadcast, so a subscriber re-running its query always observes the post-write state.
     *
     * Off by default (every dispatch re-runs its handler). Pass an options object to tune the caps: `maxEntries` (default 1000) and `maxBytes` (default 4 MiB); either accepts `Number.POSITIVE_INFINITY` to disable that cap.
     */
    public reactiveCache(config: boolean | { maxBytes?: number; maxEntries?: number } = true): this {
        this.reactiveCacheConfig = config;

        return this;
    }

    /** Ceiling on the join keys ONE relation-crossing `where` predicate may pre-resolve via semijoin before failing closed. Omit for the engine default. */
    public maxRelationKeys(limit: NonNullable<ShardConfig["maxRelationKeys"]>): this {
        this.maxRelationKeysLimit = limit;

        return this;
    }

    /**
     * Route the shard's `ctx.log` lines, `ctx.trace` spans and `ctx.metrics` measurements to a telemetry sink.
     *
     * The DO half of observability: without it every in-handler signal stays in the shard's local ring buffer (the studio Logs panel) and reaches no collector. The worker half — one `onRpc` event per dispatched RPC — is a `createWorker` option; pass the SAME sink to both via `.extend((env) => ({ observability: sink(env) }))` to correlate them.
     */
    public observability(selector: NonNullable<ShardConfig["observability"]>): this {
        this.observabilitySink = selector;

        return this;
    }

    /** Resolution policy for a relation-crossing `where` whose child is co-located in this shard: `"auto"` (cost-based, the engine default), `"always"` (inline correlated EXISTS) or `"never"` (universal semijoin). All three return identical rows. */
    public relationExistsPushDown(mode: NonNullable<ShardConfig["relationExistsPushDown"]>): this {
        this.relationExistsPushDownMode = mode;

        return this;
    }

    /** Escape hatch — merge raw `WorkerOptions` (anything not yet sugared) over the derived options at build time. The second `derived` argument is a snapshot of the options assembled so far (after `.auth(...)` etc.), so you can compose rather than clobber — e.g. wrap `derived.resolveIdentity` instead of replacing it. */
    public extend(fn: (env: Env, derived: Readonly<WorkerOptions>) => Partial<WorkerOptions>): this {
        this.extendFns.push(fn);

        return this;
    }

    /** Cloudflare Email Routing entry — exposes the top-level `email` handler. */
    public onEmail(handler: (env: Env) => (message: unknown, env: unknown, context: ExecutionContextLike) => Promise<void>): this {
        this.emailHandler = handler;

        return this;
    }

    /** Mount a whole HTTP app (`httpRouter()` from `@lunora/server`, or anything with a `fetch`) ahead of Lunora's own routes. Use this for a multi-endpoint hono app with its own CORS + error handling; `.route()` is for one-off endpoints. */
    public httpRouter(app: HttpRouterLike): this {
        this.httpRouterApp = app;

        return this;
    }

    /** Mount a custom HTTP route (e.g. an asset-serving or test endpoint). Key is `"METHOD path"`, `"path"`, or a path prefix matched by the runtime. */
    public route(key: string, handler: Route): this {
        this.routeMap[key] = handler;

        return this;
    }

    /** The shard Durable Object namespace (typically `env.SHARD`) — required: every app routes RPC + WebSocket traffic through it. */
    public shard(selector: Selector<Env, ShardNamespaceLike>): this {
        this.shardSelector = selector;

        return this;
    }

    /** Materialise the standalone Cloudflare worker + `ShardDO` class. */
    public build(): ComposedApp {
        return this.assemble();
    }

    /** Build the shard DO + compose the worker (standalone or framework-hosted), wrapping the lazy per-isolate singletons + auth init. */
    private assemble(): ComposedApp {
        const ShardDO = createShardDO({
            cdc: this.cdcEnabled,
            reactiveCache: this.reactiveCacheConfig,
            ...(this.maxRelationKeysLimit === undefined ? {} : { maxRelationKeys: this.maxRelationKeysLimit }),
            ...(this.observabilitySink === undefined ? {} : { observability: this.observabilitySink }),
            ...(this.relationExistsPushDownMode === undefined ? {} : { relationExistsPushDown: this.relationExistsPushDownMode }),
        });

        // Per-isolate singletons: the worker (and auth instance) are expensive to
        // build, so the first request constructs them and every later request on
        // the same isolate reuses them.
        let worker: LunoraWorker | null = null;

        const buildWorker = (env: Env): LunoraWorker => createWorker(this.buildWorkerOptions(env, () => null));

        const composed: ComposedApp = {
            ShardDO,
            fetch: async (request: Request, rawEnv: unknown, context: ExecutionContextLike): Promise<Response> => {
                const env = rawEnv as Env;
                worker ??= buildWorker(env);

                return worker.fetch(request, rawEnv, context);
            },
            scheduled: async (controller: ScheduledControllerLike, rawEnv: unknown, context: ExecutionContextLike): Promise<void> => {
                worker ??= buildWorker(rawEnv as Env);

                return worker.scheduled(controller, rawEnv, context);
            },
            serverQuery: (request, rawEnv, reference, args, options) => {
                worker ??= buildWorker(rawEnv as Env);

                return worker.serverQuery(request, rawEnv, reference, args, options);
            },
        };

        if (this.emailHandler) {
            const handler = this.emailHandler;

            composed.email = (message, rawEnv, context) => handler(rawEnv as Env)(message, rawEnv, context);
        }

        return composed;
    }

    /** Fan the recorded declarations into the worker-side `createWorker` options. */
    private buildWorkerOptions(env: Env, _getAuth: () => null): WorkerOptions {
        const options: WorkerOptions = {
            cronJobs: LUNORA_CRONS,
            functions: LUNORA_FUNCTIONS,
            openApiSpec,
            ...(this.httpRouterApp ? { httpRouter: this.httpRouterApp } : {}),
            routes: this.routeMap,
            shardDO: this.shardSelector?.(env) ?? (undefined as unknown as ShardNamespaceLike),
        };

        if (this.adminToken) {
            options.adminToken = this.adminToken(env);
        }

        options.listSchemaTables = () => ["nodes", "tagColors", "savedQueries", "dailyIndex", "migrateState", "ratelimit_buckets"];

        options.logArchive = resolveLogArchiveFromEnv(env);

        for (const fn of this.extendFns) {
            Object.assign(options, fn(env, { ...options }));
        }

        return options;
    }
}

/**
 * Start composing the app. Chain the capability methods, then `.build()`.
 *
 * `Env` is constrained to `object`, not `Record<string, unknown>`: an `interface Env`
 * — which is what wrangler's generated `worker-configuration.d.ts` gives you, and
 * what any app with its own bindings declares — is NOT assignable to an index
 * signature, so the stricter bound forced every real app to write
 * `type AppEnv = Env & Record<string, unknown>`. The builder only ever reads `env`
 * through the selectors you pass it, so the looser bound costs nothing.
 */
const defineApp = <Env extends object>(): AppBuilder<Env> => new AppBuilder<Env>();

export { AppBuilder, defineApp };
export type { ComposedApp, Selector };
