// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { LunoraClient } from "lunorash/client";
import { lunoraCollectionOptions } from "@lunora/db/collections";
import type { Row } from "@lunora/db";
import type { Collection } from "@tanstack/db";
import { createCollection } from "@tanstack/db";

/** Live collection for the `wholeOutline` replication shape — pass the shape's validated `args` (its partition selector). */
export const wholeOutlineCollection = (client: LunoraClient, args?: Record<string, unknown>): Collection<Row, string> =>
    createCollection(lunoraCollectionOptions({ client, shape: { args, name: "wholeOutline" } }).config);
