// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { LunoraClient, SubscriptionError } from "lunorash/client";
import { lunoraCollectionOptions } from "@lunora/db/collections";
import type { CheckpointRegistry, LunoraCollectionOptions, Row } from "@lunora/db";
import type { Collection } from "@tanstack/db";
import { createCollection } from "@tanstack/db";
import type { Doc } from "./dataModel.js";

/** Options for the `userAgentRuns` shape binding. */
export interface UserAgentRunsCollectionOptions {
        args?: {};
    /**
     * Share the optimistic-overlay gate with other collections + mutators on this
     * shard. Defaults to the shared per-shard registry, which is almost always what
     * you want — pass one only to isolate this collection's gate.
     */
    checkpoints?: CheckpointRegistry;
    /** The Lunora client to subscribe through. */
    client: LunoraClient;
    /** Row key extractor — defaults to `row._id`. Override when the app keys rows by a natural column. */
    getKey?: (row: Doc<"runs"> & Row) => string;
    /** `"eager"` starts syncing at creation; `"lazy"` (default) on the first subscriber. */
    load?: "eager" | "lazy";
    /** Notified when the underlying subscription errors; the collection always leaves `loading`. */
    onError?: (error: SubscriptionError) => void;
    /** Routes the subscription to a shard's DO. **Required for a `.shardBy()` table** — without it the watermark lands in the default bucket. */
    shardKey?: string;
}

/**
 * Collection options for the `userAgentRuns` replication shape: `config` for
 * `createCollection`, plus the `checkpoints` registry to hand `bindMutators` and
 * `scope` to re-point the subscription.
 */
export const userAgentRunsCollectionOptions = (options: UserAgentRunsCollectionOptions): LunoraCollectionOptions<Doc<"runs"> & Row> =>
    lunoraCollectionOptions<Doc<"runs"> & Row>({
        client: options.client,
        ...(options.checkpoints === undefined ? {} : { checkpoints: options.checkpoints }),
        ...(options.getKey === undefined ? {} : { getKey: options.getKey }),
        ...(options.load === undefined ? {} : { load: options.load }),
        ...(options.onError === undefined ? {} : { onError: options.onError }),
        ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }),
        shape: { args: options.args, name: "userAgentRuns", ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }) },
    });

/** Live collection for the `userAgentRuns` shape, with its sync controls. */
export const userAgentRunsCollection = (
    options: UserAgentRunsCollectionOptions,
): { checkpoints: CheckpointRegistry; collection: Collection<Doc<"runs"> & Row, string>; scope: (args?: {}) => void } => {
    const { checkpoints, config, scope } = userAgentRunsCollectionOptions(options);

    return { checkpoints, collection: createCollection(config), scope };
};

/** Options for the `userDailyIndex` shape binding. */
export interface UserDailyIndexCollectionOptions {
        args?: {};
    /**
     * Share the optimistic-overlay gate with other collections + mutators on this
     * shard. Defaults to the shared per-shard registry, which is almost always what
     * you want — pass one only to isolate this collection's gate.
     */
    checkpoints?: CheckpointRegistry;
    /** The Lunora client to subscribe through. */
    client: LunoraClient;
    /** Row key extractor — defaults to `row._id`. Override when the app keys rows by a natural column. */
    getKey?: (row: Doc<"dailyIndex"> & Row) => string;
    /** `"eager"` starts syncing at creation; `"lazy"` (default) on the first subscriber. */
    load?: "eager" | "lazy";
    /** Notified when the underlying subscription errors; the collection always leaves `loading`. */
    onError?: (error: SubscriptionError) => void;
    /** Routes the subscription to a shard's DO. **Required for a `.shardBy()` table** — without it the watermark lands in the default bucket. */
    shardKey?: string;
}

/**
 * Collection options for the `userDailyIndex` replication shape: `config` for
 * `createCollection`, plus the `checkpoints` registry to hand `bindMutators` and
 * `scope` to re-point the subscription.
 */
export const userDailyIndexCollectionOptions = (options: UserDailyIndexCollectionOptions): LunoraCollectionOptions<Doc<"dailyIndex"> & Row> =>
    lunoraCollectionOptions<Doc<"dailyIndex"> & Row>({
        client: options.client,
        ...(options.checkpoints === undefined ? {} : { checkpoints: options.checkpoints }),
        ...(options.getKey === undefined ? {} : { getKey: options.getKey }),
        ...(options.load === undefined ? {} : { load: options.load }),
        ...(options.onError === undefined ? {} : { onError: options.onError }),
        ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }),
        shape: { args: options.args, name: "userDailyIndex", ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }) },
    });

/** Live collection for the `userDailyIndex` shape, with its sync controls. */
export const userDailyIndexCollection = (
    options: UserDailyIndexCollectionOptions,
): { checkpoints: CheckpointRegistry; collection: Collection<Doc<"dailyIndex"> & Row, string>; scope: (args?: {}) => void } => {
    const { checkpoints, config, scope } = userDailyIndexCollectionOptions(options);

    return { checkpoints, collection: createCollection(config), scope };
};

/** Options for the `userSavedQueries` shape binding. */
export interface UserSavedQueriesCollectionOptions {
        args?: {};
    /**
     * Share the optimistic-overlay gate with other collections + mutators on this
     * shard. Defaults to the shared per-shard registry, which is almost always what
     * you want — pass one only to isolate this collection's gate.
     */
    checkpoints?: CheckpointRegistry;
    /** The Lunora client to subscribe through. */
    client: LunoraClient;
    /** Row key extractor — defaults to `row._id`. Override when the app keys rows by a natural column. */
    getKey?: (row: Doc<"savedQueries"> & Row) => string;
    /** `"eager"` starts syncing at creation; `"lazy"` (default) on the first subscriber. */
    load?: "eager" | "lazy";
    /** Notified when the underlying subscription errors; the collection always leaves `loading`. */
    onError?: (error: SubscriptionError) => void;
    /** Routes the subscription to a shard's DO. **Required for a `.shardBy()` table** — without it the watermark lands in the default bucket. */
    shardKey?: string;
}

/**
 * Collection options for the `userSavedQueries` replication shape: `config` for
 * `createCollection`, plus the `checkpoints` registry to hand `bindMutators` and
 * `scope` to re-point the subscription.
 */
export const userSavedQueriesCollectionOptions = (options: UserSavedQueriesCollectionOptions): LunoraCollectionOptions<Doc<"savedQueries"> & Row> =>
    lunoraCollectionOptions<Doc<"savedQueries"> & Row>({
        client: options.client,
        ...(options.checkpoints === undefined ? {} : { checkpoints: options.checkpoints }),
        ...(options.getKey === undefined ? {} : { getKey: options.getKey }),
        ...(options.load === undefined ? {} : { load: options.load }),
        ...(options.onError === undefined ? {} : { onError: options.onError }),
        ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }),
        shape: { args: options.args, name: "userSavedQueries", ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }) },
    });

/** Live collection for the `userSavedQueries` shape, with its sync controls. */
export const userSavedQueriesCollection = (
    options: UserSavedQueriesCollectionOptions,
): { checkpoints: CheckpointRegistry; collection: Collection<Doc<"savedQueries"> & Row, string>; scope: (args?: {}) => void } => {
    const { checkpoints, config, scope } = userSavedQueriesCollectionOptions(options);

    return { checkpoints, collection: createCollection(config), scope };
};

/** Options for the `userTagColors` shape binding. */
export interface UserTagColorsCollectionOptions {
        args?: {};
    /**
     * Share the optimistic-overlay gate with other collections + mutators on this
     * shard. Defaults to the shared per-shard registry, which is almost always what
     * you want — pass one only to isolate this collection's gate.
     */
    checkpoints?: CheckpointRegistry;
    /** The Lunora client to subscribe through. */
    client: LunoraClient;
    /** Row key extractor — defaults to `row._id`. Override when the app keys rows by a natural column. */
    getKey?: (row: Doc<"tagColors"> & Row) => string;
    /** `"eager"` starts syncing at creation; `"lazy"` (default) on the first subscriber. */
    load?: "eager" | "lazy";
    /** Notified when the underlying subscription errors; the collection always leaves `loading`. */
    onError?: (error: SubscriptionError) => void;
    /** Routes the subscription to a shard's DO. **Required for a `.shardBy()` table** — without it the watermark lands in the default bucket. */
    shardKey?: string;
}

/**
 * Collection options for the `userTagColors` replication shape: `config` for
 * `createCollection`, plus the `checkpoints` registry to hand `bindMutators` and
 * `scope` to re-point the subscription.
 */
export const userTagColorsCollectionOptions = (options: UserTagColorsCollectionOptions): LunoraCollectionOptions<Doc<"tagColors"> & Row> =>
    lunoraCollectionOptions<Doc<"tagColors"> & Row>({
        client: options.client,
        ...(options.checkpoints === undefined ? {} : { checkpoints: options.checkpoints }),
        ...(options.getKey === undefined ? {} : { getKey: options.getKey }),
        ...(options.load === undefined ? {} : { load: options.load }),
        ...(options.onError === undefined ? {} : { onError: options.onError }),
        ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }),
        shape: { args: options.args, name: "userTagColors", ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }) },
    });

/** Live collection for the `userTagColors` shape, with its sync controls. */
export const userTagColorsCollection = (
    options: UserTagColorsCollectionOptions,
): { checkpoints: CheckpointRegistry; collection: Collection<Doc<"tagColors"> & Row, string>; scope: (args?: {}) => void } => {
    const { checkpoints, config, scope } = userTagColorsCollectionOptions(options);

    return { checkpoints, collection: createCollection(config), scope };
};

/** Options for the `wholeOutline` shape binding. */
export interface WholeOutlineCollectionOptions {
        args?: {};
    /**
     * Share the optimistic-overlay gate with other collections + mutators on this
     * shard. Defaults to the shared per-shard registry, which is almost always what
     * you want — pass one only to isolate this collection's gate.
     */
    checkpoints?: CheckpointRegistry;
    /** The Lunora client to subscribe through. */
    client: LunoraClient;
    /** Row key extractor — defaults to `row._id`. Override when the app keys rows by a natural column. */
    getKey?: (row: Doc<"nodes"> & Row) => string;
    /** `"eager"` starts syncing at creation; `"lazy"` (default) on the first subscriber. */
    load?: "eager" | "lazy";
    /** Notified when the underlying subscription errors; the collection always leaves `loading`. */
    onError?: (error: SubscriptionError) => void;
    /** Routes the subscription to a shard's DO. **Required for a `.shardBy()` table** — without it the watermark lands in the default bucket. */
    shardKey?: string;
}

/**
 * Collection options for the `wholeOutline` replication shape: `config` for
 * `createCollection`, plus the `checkpoints` registry to hand `bindMutators` and
 * `scope` to re-point the subscription.
 */
export const wholeOutlineCollectionOptions = (options: WholeOutlineCollectionOptions): LunoraCollectionOptions<Doc<"nodes"> & Row> =>
    lunoraCollectionOptions<Doc<"nodes"> & Row>({
        client: options.client,
        ...(options.checkpoints === undefined ? {} : { checkpoints: options.checkpoints }),
        ...(options.getKey === undefined ? {} : { getKey: options.getKey }),
        ...(options.load === undefined ? {} : { load: options.load }),
        ...(options.onError === undefined ? {} : { onError: options.onError }),
        ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }),
        shape: { args: options.args, name: "wholeOutline", ...(options.shardKey === undefined ? {} : { shardKey: options.shardKey }) },
    });

/** Live collection for the `wholeOutline` shape, with its sync controls. */
export const wholeOutlineCollection = (
    options: WholeOutlineCollectionOptions,
): { checkpoints: CheckpointRegistry; collection: Collection<Doc<"nodes"> & Row, string>; scope: (args?: {}) => void } => {
    const { checkpoints, config, scope } = wholeOutlineCollectionOptions(options);

    return { checkpoints, collection: createCollection(config), scope };
};
