// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

/**
 * One scheduled cron invocation. Exactly one target is set: `functionPath` is
 * the `namespace:fn` dispatch ref (matches `__lunoraRef`), invoked on the
 * shard; `workflow` is a `WORKFLOW_*` binding name whose durable workflow is
 * started fresh per fire. `args` are forwarded verbatim (a workflow's become
 * its `params`).
 */
export interface LunoraCronJob {
    args: Record<string, unknown>;
    functionPath?: string;
    name: string;
    workflow?: string;
}

/**
 * Deduplicated cron schedules — mirror of wrangler's `triggers.crons`. The
 * Lunora vite plugin keeps `wrangler.jsonc` in sync with this array.
 */
export const LUNORA_CRON_TRIGGERS: ReadonlyArray<string> = [];

/**
 * Dispatcher map keyed by cron expression. The Worker's `scheduled()` handler
 * looks up `event.cron` here and dispatches every job in the list.
 */
export const LUNORA_CRONS: Record<string, ReadonlyArray<LunoraCronJob>> = {};
