// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

export type TableName = "nodes" | "tagColors" | "savedQueries" | "dailyIndex" | "migrateState" | "retirementState" | "ratelimit_buckets";

/**
 * The tables **this app declared** — every {@link TableName} except those an add-on
 * contributed through `defineSchema(...).extend(...)`.
 *
 * An add-on's tables are real tables and stay in `TableName` (they are queryable,
 * they appear in `DataModel`), but an app enumerating "my tables" should not have to
 * know they exist: an account-deletion sweep, an export, a migration allowlist, or a
 * helper generic over a table union is about the app's own data, and every add-on
 * added or removed would otherwise silently change the correct answer.
 *
 * ```ts
 * // Doesn't need to mention `ratelimit_buckets`, and won't drift when an add-on lands.
 * const EXPORTED: readonly AppTableName[] = ["nodes", "tagColors"];
 * ```
 */
export type AppTableName = "nodes" | "tagColors" | "savedQueries" | "dailyIndex" | "migrateState" | "retirementState";

export type Id<TName extends string> = string & { readonly __table: TName };

export interface Doc_nodes {
    _id: Id<"nodes">;
    _creationTime: number;
    parentId: string;
    prevSiblingId: string;
    text: string;
    isTask: boolean;
    completed: boolean;
    collapsed: boolean;
    bookmarkedAt: number;
    mirrorOf: string;
    createdAt: number;
    updatedAt: number;
    origin: string;
    kind: "paragraph";
    userId: string;
}

export interface Doc_tagColors {
    _id: Id<"tagColors">;
    _creationTime: number;
    tag: string;
    color: string;
    userId: string;
}

export interface Doc_savedQueries {
    _id: Id<"savedQueries">;
    _creationTime: number;
    name: string;
    query: string;
    createdAt: number;
    userId: string;
}

export interface Doc_dailyIndex {
    _id: Id<"dailyIndex">;
    _creationTime: number;
    key: string;
    nodeId: string;
    touchedAt: number;
    userId: string;
}

export interface Doc_migrateState {
    _id: Id<"migrateState">;
    _creationTime: number;
    userId: string;
    nodesAt: number;
    kvAt: number;
}

export interface Doc_retirementState {
    _id: Id<"retirementState">;
    _creationTime: number;
    userId: string;
    migrationId: string;
    status: "frozen" | "retired";
    updatedAt: number;
}

export interface Doc_ratelimit_buckets {
    _id: Id<"ratelimit_buckets">;
    _creationTime: number;
    key: string;
    value: number;
    ts: number;
    prev?: number;
}

export interface DataModel {
    nodes: Doc_nodes;
    tagColors: Doc_tagColors;
    savedQueries: Doc_savedQueries;
    dailyIndex: Doc_dailyIndex;
    migrateState: Doc_migrateState;
    retirementState: Doc_retirementState;
    ratelimit_buckets: Doc_ratelimit_buckets;
}

export type Doc<T extends keyof DataModel> = DataModel[T];

/**
 * Per-table index name union. `never` for tables without secondary indexes.
 * Used by `TableReader.withIndex()` to constrain callers to declared names.
 */
export interface IndexNamesByTable {
    nodes: "by_parent";
    tagColors: "by_tag";
    savedQueries: never;
    dailyIndex: "by_key";
    migrateState: never;
    retirementState: never;
    ratelimit_buckets: "by_key";
}

export type IndexName<T extends keyof DataModel> = IndexNamesByTable[T];

/** Per-table search-index name union. `never` for tables without searchIndex. */
export interface SearchIndexNamesByTable {
    nodes: never;
    tagColors: never;
    savedQueries: never;
    dailyIndex: never;
    migrateState: never;
    retirementState: never;
    ratelimit_buckets: never;
}

export type SearchIndexName<T extends keyof DataModel> = SearchIndexNamesByTable[T];

/** Per-table rank-index name union. `never` for tables without a rankIndex. */
export interface RankIndexNamesByTable {
    nodes: never;
    tagColors: never;
    savedQueries: never;
    dailyIndex: never;
    migrateState: never;
    retirementState: never;
    ratelimit_buckets: never;
}

export type RankIndexName<T extends keyof DataModel> = RankIndexNamesByTable[T];

/** Per-table geo-index name union. `never` for tables without a geoIndex. */
export interface GeoIndexNamesByTable {
    nodes: never;
    tagColors: never;
    savedQueries: never;
    dailyIndex: never;
    migrateState: never;
    retirementState: never;
    ratelimit_buckets: never;
}

export type GeoIndexName<T extends keyof DataModel> = GeoIndexNamesByTable[T];

/** Union of declared vector index names. `never` when none are declared. */
export type VectorIndexName = never;

export interface Insert_nodes {
    _id?: Id<"nodes">;
    _creationTime?: number;
    parentId: string;
    prevSiblingId: string;
    text: string;
    isTask: boolean;
    completed: boolean;
    collapsed: boolean;
    bookmarkedAt: number;
    mirrorOf: string;
    createdAt: number;
    updatedAt: number;
    origin: string;
    kind: "paragraph";
    userId: string;
}

export interface Insert_tagColors {
    _id?: Id<"tagColors">;
    _creationTime?: number;
    tag: string;
    color: string;
    userId: string;
}

export interface Insert_savedQueries {
    _id?: Id<"savedQueries">;
    _creationTime?: number;
    name: string;
    query: string;
    createdAt: number;
    userId: string;
}

export interface Insert_dailyIndex {
    _id?: Id<"dailyIndex">;
    _creationTime?: number;
    key: string;
    nodeId: string;
    touchedAt: number;
    userId: string;
}

export interface Insert_migrateState {
    _id?: Id<"migrateState">;
    _creationTime?: number;
    userId: string;
    nodesAt: number;
    kvAt: number;
}

export interface Insert_retirementState {
    _id?: Id<"retirementState">;
    _creationTime?: number;
    userId: string;
    migrationId: string;
    status: "frozen" | "retired";
    updatedAt: number;
}

export interface Insert_ratelimit_buckets {
    _id?: Id<"ratelimit_buckets">;
    _creationTime?: number;
    key: string;
    value: number;
    ts: number;
    prev?: number;
}

/** Per-table insert shape, accepted by `ctx.db.<table>.insert(...)`. */
export interface InsertModel {
    nodes: Insert_nodes;
    tagColors: Insert_tagColors;
    savedQueries: Insert_savedQueries;
    dailyIndex: Insert_dailyIndex;
    migrateState: Insert_migrateState;
    retirementState: Insert_retirementState;
    ratelimit_buckets: Insert_ratelimit_buckets;
}

export type Insert<T extends keyof DataModel> = InsertModel[T];

/**
 * Phantom relation descriptors. They carry the relation kind and target table
 * as type parameters only — there is no runtime value — so the `with` argument
 * and its return type can be inferred from {@link Relations}.
 */
export interface OneRelation<Target extends keyof DataModel> {
    readonly __relationKind: "one";
    readonly __target: Target;
}

export interface ManyRelation<Target extends keyof DataModel> {
    readonly __relationKind: "many";
    readonly __target: Target;
}

/** Per-table relation map keyed by accessor name. `{}` for tables with none. */
export interface Relations {
    nodes: {};
    tagColors: {};
    savedQueries: {};
    dailyIndex: {};
    migrateState: {};
    retirementState: {};
    ratelimit_buckets: {};
}

