// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { index, integer, real, sqliteTable, text } from "lunorash/server/drizzle";

export const nodes = sqliteTable("nodes", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    parentId: text("parentId").notNull(),
    prevSiblingId: text("prevSiblingId").notNull(),
    text: text("text").notNull(),
    isTask: integer("isTask", { mode: "boolean" }).notNull(),
    completed: integer("completed", { mode: "boolean" }).notNull(),
    collapsed: integer("collapsed", { mode: "boolean" }).notNull(),
    bookmarkedAt: real("bookmarkedAt").notNull(),
    mirrorOf: text("mirrorOf").notNull(),
    createdAt: real("createdAt").notNull(),
    updatedAt: real("updatedAt").notNull(),
    origin: text("origin").notNull(),
    kind: text("kind").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_parent: index("by_parent").on(t.parentId),
}));

export const tagColors = sqliteTable("tagColors", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    tag: text("tag").notNull(),
    color: text("color").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_tag: index("by_tag").on(t.tag),
}));

export const savedQueries = sqliteTable("savedQueries", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    name: text("name").notNull(),
    query: text("query").notNull(),
    createdAt: real("createdAt").notNull(),
    userId: text("userId").notNull(),
});

export const dailyIndex = sqliteTable("dailyIndex", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    key: text("key").notNull(),
    nodeId: text("nodeId").notNull(),
    touchedAt: real("touchedAt").notNull(),
    userId: text("userId").notNull(),
}, (t) => ({
    by_key: index("by_key").on(t.key),
}));

export const migrateState = sqliteTable("migrateState", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    userId: text("userId").notNull(),
    nodesAt: real("nodesAt").notNull(),
    kvAt: real("kvAt").notNull(),
});

export const runs = sqliteTable("runs", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    userId: text("userId").notNull(),
    questionNodeId: text("questionNodeId").notNull(),
    status: text("status", { mode: "json" }).$type<"running" | "completed" | "cancelled" | "error">().notNull(),
    partialText: text("partialText").notNull(),
    answerRootId: text("answerRootId").notNull(),
    answerHash: text("answerHash").notNull(),
    error: text("error").notNull(),
    createdAt: real("createdAt").notNull(),
    updatedAt: real("updatedAt").notNull(),
}, (t) => ({
    by_status: index("by_status").on(t.status),
    by_question: index("by_question").on(t.questionNodeId),
}));

export const ratelimit_buckets = sqliteTable("ratelimit_buckets", {
    _id: text("_id").primaryKey(),
    _creationTime: integer("_creationTime").notNull(),
    key: text("key").notNull(),
    value: real("value").notNull(),
    ts: real("ts").notNull(),
    prev: real("prev"),
}, (t) => ({
    by_key: index("by_key").on(t.key),
}));
