// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import * as lunora_mcp_0 from "../mcp.js";
import * as lunora_mutators_1 from "../mutators.js";
import * as lunora_shapes_2 from "../shapes.js";

import { DEFER_VALIDATION as DEFER, installCompiledValidatorMap } from "lunorash/values";
import type { RegisteredShape } from "lunorash/server";
import { LunoraError } from "lunorash/server";
import type { ActionCtx, MutationCtx, QueryCtx } from "./server.js";

/**
 * Single registered function, narrowed to the shape `handleRpc` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to `unknown` so a single map can host every
 * registered function.
 */
export interface RegisteredLunoraFunction {
    kind: "action" | "mutation" | "query" | "stream";
    args: Record<string, unknown>;
    /**
     * For `"action" | "mutation" | "query"` the handler is awaited and its result returned.
     * For `"stream"` the handler returns an `AsyncIterable` synchronously and takes an
     * `AbortSignal` as a third argument — the runtime drives it frame-by-frame.
     */
    handler: ((context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown) | ((context: unknown, args: Record<string, unknown>, signal?: AbortSignal) => AsyncIterable<unknown>);
    /** `"internal"` functions are rejected on the external RPC path; absence === public. */
    visibility?: "internal" | "public";
}

/**
 * Static dispatch table. The key matches the `__lunoraRef` the client
 * emits (`api[namespace][fn].__lunoraRef === "namespace:fn"`).
 */
export const LUNORA_FUNCTIONS: Record<string, RegisteredLunoraFunction> = {
    "mcp:applyChangeOps": lunora_mcp_0.applyChangeOps as unknown as RegisteredLunoraFunction,
    "mcp:listDailyIndex": lunora_mcp_0.listDailyIndex as unknown as RegisteredLunoraFunction,
    "mcp:listNodes": lunora_mcp_0.listNodes as unknown as RegisteredLunoraFunction,
    "mutators:appendChild": lunora_mutators_1.appendChild as unknown as RegisteredLunoraFunction,
    "mutators:claimDailyMapping": lunora_mutators_1.claimDailyMapping as unknown as RegisteredLunoraFunction,
    "mutators:deleteDailyMapping": lunora_mutators_1.deleteDailyMapping as unknown as RegisteredLunoraFunction,
    "mutators:deleteSavedQuery": lunora_mutators_1.deleteSavedQuery as unknown as RegisteredLunoraFunction,
    "mutators:deleteTagColor": lunora_mutators_1.deleteTagColor as unknown as RegisteredLunoraFunction,
    "mutators:hello": lunora_mutators_1.hello as unknown as RegisteredLunoraFunction,
    "mutators:importNodes": lunora_mutators_1.importNodes as unknown as RegisteredLunoraFunction,
    "mutators:indent": lunora_mutators_1.indent as unknown as RegisteredLunoraFunction,
    "mutators:indentMany": lunora_mutators_1.indentMany as unknown as RegisteredLunoraFunction,
    "mutators:insertChildAtStart": lunora_mutators_1.insertChildAtStart as unknown as RegisteredLunoraFunction,
    "mutators:insertSibling": lunora_mutators_1.insertSibling as unknown as RegisteredLunoraFunction,
    "mutators:materializeDailyNodes": lunora_mutators_1.materializeDailyNodes as unknown as RegisteredLunoraFunction,
    "mutators:mirrorNode": lunora_mutators_1.mirrorNode as unknown as RegisteredLunoraFunction,
    "mutators:moveMany": lunora_mutators_1.moveMany as unknown as RegisteredLunoraFunction,
    "mutators:moveNode": lunora_mutators_1.moveNode as unknown as RegisteredLunoraFunction,
    "mutators:outdent": lunora_mutators_1.outdent as unknown as RegisteredLunoraFunction,
    "mutators:outdentMany": lunora_mutators_1.outdentMany as unknown as RegisteredLunoraFunction,
    "mutators:patchSavedQuery": lunora_mutators_1.patchSavedQuery as unknown as RegisteredLunoraFunction,
    "mutators:removeMany": lunora_mutators_1.removeMany as unknown as RegisteredLunoraFunction,
    "mutators:removeNode": lunora_mutators_1.removeNode as unknown as RegisteredLunoraFunction,
    "mutators:restoreNodes": lunora_mutators_1.restoreNodes as unknown as RegisteredLunoraFunction,
    "mutators:seedIfEmpty": lunora_mutators_1.seedIfEmpty as unknown as RegisteredLunoraFunction,
    "mutators:setBookmarkedAt": lunora_mutators_1.setBookmarkedAt as unknown as RegisteredLunoraFunction,
    "mutators:setCollapsed": lunora_mutators_1.setCollapsed as unknown as RegisteredLunoraFunction,
    "mutators:setCompleted": lunora_mutators_1.setCompleted as unknown as RegisteredLunoraFunction,
    "mutators:setIsTask": lunora_mutators_1.setIsTask as unknown as RegisteredLunoraFunction,
    "mutators:setKind": lunora_mutators_1.setKind as unknown as RegisteredLunoraFunction,
    "mutators:setText": lunora_mutators_1.setText as unknown as RegisteredLunoraFunction,
    "mutators:splitNode": lunora_mutators_1.splitNode as unknown as RegisteredLunoraFunction,
    "mutators:upsertDailyMapping": lunora_mutators_1.upsertDailyMapping as unknown as RegisteredLunoraFunction,
    "mutators:upsertSavedQuery": lunora_mutators_1.upsertSavedQuery as unknown as RegisteredLunoraFunction,
    "mutators:upsertTagColor": lunora_mutators_1.upsertTagColor as unknown as RegisteredLunoraFunction,
};

/**
 * AOT-compiled argument validators (Worker-safe, no `eval`). Each is installed
 * onto its function's live `.args` object and consulted by the interpreted
 * parser as a zero-allocation fast path; anything it can't model is deferred.
 */
installCompiledValidatorMap(lunora_mcp_0.listDailyIndex.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["userId"] !== "string") return DEFER;
return { "userId": source["userId"] };
});
installCompiledValidatorMap(lunora_mcp_0.listNodes.args, (source) => {
if (typeof source !== "object" || source === null || Array.isArray(source)) return DEFER;
if (typeof source["userId"] !== "string") return DEFER;
return { "userId": source["userId"] };
});

/**
 * Replication-shape registry — one entry per `defineShape` in `lunora/shapes.ts`.
 * The generated ShardDO's `resolveShape` override looks a shape up by name and
 * evaluates its trusted `compileWhere(ctx, args)` to authorize + scope a
 * `shape_subscribe` (reads-as-permissions).
 */
export const LUNORA_SHAPES: Record<string, RegisteredShape> = {
    "userDailyIndex": lunora_shapes_2.userDailyIndex as unknown as RegisteredShape,
    "userSavedQueries": lunora_shapes_2.userSavedQueries as unknown as RegisteredShape,
    "userTagColors": lunora_shapes_2.userTagColors as unknown as RegisteredShape,
    "wholeOutline": lunora_shapes_2.wholeOutline as unknown as RegisteredShape,
};

/**
 * Custom-mutator function paths — the `LUNORA_FUNCTIONS` keys the generated
 * ShardDO's `isCustomMutator` override routes through the client-watermark push
 * protocol (`x-lunora-client-id`/`x-lunora-client-seq` ordering).
 */
export const LUNORA_MUTATOR_PATHS: ReadonlySet<string> = new Set(["mutators:appendChild", "mutators:claimDailyMapping", "mutators:deleteDailyMapping", "mutators:deleteSavedQuery", "mutators:deleteTagColor", "mutators:hello", "mutators:importNodes", "mutators:indent", "mutators:indentMany", "mutators:insertChildAtStart", "mutators:insertSibling", "mutators:materializeDailyNodes", "mutators:mirrorNode", "mutators:moveMany", "mutators:moveNode", "mutators:outdent", "mutators:outdentMany", "mutators:patchSavedQuery", "mutators:removeMany", "mutators:removeNode", "mutators:restoreNodes", "mutators:seedIfEmpty", "mutators:setBookmarkedAt", "mutators:setCollapsed", "mutators:setCompleted", "mutators:setIsTask", "mutators:setKind", "mutators:setText", "mutators:splitNode", "mutators:upsertDailyMapping", "mutators:upsertSavedQuery", "mutators:upsertTagColor"]);

/**
 * Connection-lifecycle manifest: the function paths the generated ShardDO
 * dispatches when a client's WebSocket connects (`connect`) or disconnects
 * (`disconnect`). Each path also resolves through {@link LUNORA_FUNCTIONS}; the
 * DO runs every hook under the socket's verified identity via system dispatch.
 */
export const LUNORA_LIFECYCLE_HOOKS: { connect: readonly string[]; disconnect: readonly string[] } = {
    connect: [],
    disconnect: [],
};

/**
 * Resolve and invoke a registered function from an external caller. Throws a
 * LunoraError-shaped object (404) when the path is unknown — the runtime's
 * structural error mapper turns that into the right HTTP status. Internal
 * functions are treated as not-found so their existence never leaks to clients.
 */
export const dispatchLunoraFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered || registered.visibility === "internal") {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return registered.handler(context, args);
};

/**
 * A handler context accepted by {@link createCaller}. The runtime context the
 * shard DO builds is uniform across kinds, so any handler's `ctx` works here.
 */
export type CallerCtx = ActionCtx | MutationCtx | QueryCtx;

/**
 * Typed, in-process server-to-server caller. Every registered function — public
 * *and* internal — is reachable; each call dispatches against the same shard
 * with the supplied `context`, exactly like `ctx.runQuery`/`runMutation`/
 * `runAction` but without re-stating the function path.
 */
export interface Caller {
    mcp: {
        applyChangeOps: (args: { userId: string; ops: Array<unknown> }) => Promise<{ count: number; deletes?: undefined; inserts?: undefined; patches?: undefined; } | { count: number; deletes: number; inserts: number; patches: number; }>;
        listDailyIndex: (args: { userId: string }) => Promise<{ key: string; nodeId: string; }[]>;
        listNodes: (args: { userId: string }) => Promise<{ id: string; parentId: string | null; prevSiblingId: string | null; text: string; isTask: boolean; completed: boolean; collapsed: boolean; bookmarkedAt: number | null; mirrorOf: string | null; createdAt: number; updatedAt: number; origin: string | null; kind: "paragraph" | null }[]>;
    };
}

const callRegistered = async <R>(context: CallerCtx, functionPath: string, args: Record<string, unknown> | undefined): Promise<R> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered) {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return (await registered.handler(context, args ?? {})) as R;
};

/** Build a {@link Caller} bound to `context` (typically a handler's `ctx`). */
export const createCaller = (context: CallerCtx): Caller => ({
    mcp: {
        applyChangeOps: (args) => callRegistered(context, "mcp:applyChangeOps", args),
        listDailyIndex: (args) => callRegistered(context, "mcp:listDailyIndex", args),
        listNodes: (args) => callRegistered(context, "mcp:listNodes", args),
    },
});

/**
 * Single registered data migration, narrowed to the shape the per-shard runner
 * consumes. `up`/`down` are erased to a structural transform; the authoring
 * validation lives in `defineMigration`.
 */
export interface RegisteredDataMigration {
    batchSize?: number;
    down?: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
    id: string;
    table: string;
    up: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
}

/**
 * Registry of online data migrations keyed by `defineMigration`'s `id`. The
 * shard DO's admin RPC and the CLI resolve migrations to run through this map.
 */
export const LUNORA_MIGRATIONS: Record<string, RegisteredDataMigration> = {};
