// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import * as lunora_mutators_0 from "../mutators.js";
import * as lunora_shapes_1 from "../shapes.js";

import type { RegisteredShape } from "lunorash/server";
import { LunoraError } from "lunorash/server";
import type { ActionCtx, MutationCtx, QueryCtx } from "./server.js";

/**
 * Single registered function, narrowed to the shape `handleRpc` needs.
 * The real argument validators / return types are checked elsewhere — at
 * the dispatch site we erase to `unknown` so a single map can host every
 * registered function.
 */
export interface RegisteredLunoraFunction {
    kind: "action" | "mutation" | "query" | "stream";
    args: Record<string, unknown>;
    /**
     * For `"action" | "mutation" | "query"` the handler is awaited and its result returned.
     * For `"stream"` the handler returns an `AsyncIterable` synchronously and takes an
     * `AbortSignal` as a third argument — the runtime drives it frame-by-frame.
     */
    handler: ((context: unknown, args: Record<string, unknown>) => Promise<unknown> | unknown) | ((context: unknown, args: Record<string, unknown>, signal?: AbortSignal) => AsyncIterable<unknown>);
    /** `"internal"` functions are rejected on the external RPC path; absence === public. */
    visibility?: "internal" | "public";
}

/**
 * Static dispatch table. The key matches the `__lunoraRef` the client
 * emits (`api[namespace][fn].__lunoraRef === "namespace:fn"`).
 */
export const LUNORA_FUNCTIONS: Record<string, RegisteredLunoraFunction> = {
    "mutators:hello": lunora_mutators_0.hello as unknown as RegisteredLunoraFunction,
    "mutators:indent": lunora_mutators_0.indent as unknown as RegisteredLunoraFunction,
    "mutators:insertSibling": lunora_mutators_0.insertSibling as unknown as RegisteredLunoraFunction,
    "mutators:outdent": lunora_mutators_0.outdent as unknown as RegisteredLunoraFunction,
    "mutators:removeNode": lunora_mutators_0.removeNode as unknown as RegisteredLunoraFunction,
    "mutators:seedIfEmpty": lunora_mutators_0.seedIfEmpty as unknown as RegisteredLunoraFunction,
    "mutators:setText": lunora_mutators_0.setText as unknown as RegisteredLunoraFunction,
};

/**
 * Replication-shape registry — one entry per `defineShape` in `lunora/shapes.ts`.
 * The generated ShardDO's `resolveShape` override looks a shape up by name and
 * evaluates its trusted `compileWhere(ctx, args)` to authorize + scope a
 * `shape_subscribe` (reads-as-permissions).
 */
export const LUNORA_SHAPES: Record<string, RegisteredShape> = {
    "wholeOutline": lunora_shapes_1.wholeOutline as unknown as RegisteredShape,
};

/**
 * Custom-mutator function paths — the `LUNORA_FUNCTIONS` keys the generated
 * ShardDO's `isCustomMutator` override routes through the client-watermark push
 * protocol (`x-lunora-client-id`/`x-lunora-client-seq` ordering).
 */
export const LUNORA_MUTATOR_PATHS: ReadonlySet<string> = new Set(["mutators:hello", "mutators:indent", "mutators:insertSibling", "mutators:outdent", "mutators:removeNode", "mutators:seedIfEmpty", "mutators:setText"]);

/**
 * Connection-lifecycle manifest: the function paths the generated ShardDO
 * dispatches when a client's WebSocket connects (`connect`) or disconnects
 * (`disconnect`). Each path also resolves through {@link LUNORA_FUNCTIONS}; the
 * DO runs every hook under the socket's verified identity via system dispatch.
 */
export const LUNORA_LIFECYCLE_HOOKS: { connect: readonly string[]; disconnect: readonly string[] } = {
    connect: [],
    disconnect: [],
};

/**
 * Resolve and invoke a registered function from an external caller. Throws a
 * LunoraError-shaped object (404) when the path is unknown — the runtime's
 * structural error mapper turns that into the right HTTP status. Internal
 * functions are treated as not-found so their existence never leaks to clients.
 */
export const dispatchLunoraFunction = async (functionPath: string, context: unknown, args: Record<string, unknown>): Promise<unknown> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered || registered.visibility === "internal") {
        throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
    }

    return registered.handler(context, args);
};

/**
 * A handler context accepted by {@link createCaller}. The runtime context the
 * shard DO builds is uniform across kinds, so any handler's `ctx` works here.
 */
export type CallerCtx = ActionCtx | MutationCtx | QueryCtx;

/**
 * Typed, in-process server-to-server caller. Every registered function — public
 * *and* internal — is reachable; each call dispatches against the same shard
 * with the supplied `context`, exactly like `ctx.runQuery`/`runMutation`/
 * `runAction` but without re-stating the function path.
 */
export interface Caller {}

/** Build a {@link Caller} bound to `context` (typically a handler's `ctx`). */
export const createCaller = (_context: CallerCtx): Caller => ({});

/**
 * Single registered data migration, narrowed to the shape the per-shard runner
 * consumes. `up`/`down` are erased to a structural transform; the authoring
 * validation lives in `defineMigration`.
 */
export interface RegisteredDataMigration {
    batchSize?: number;
    down?: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
    id: string;
    table: string;
    up: (document: Record<string, unknown>) => Record<string, unknown> | undefined;
}

/**
 * Registry of online data migrations keyed by `defineMigration`'s `id`. The
 * shard DO's admin RPC and the CLI resolve migrations to run through this map.
 */
export const LUNORA_MIGRATIONS: Record<string, RegisteredDataMigration> = {};
