// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

export const openApiSpec: Record<string, unknown> = {
    "components": {
        "responses": {
            "LunoraError": {
                "content": {
                    "application/json": {
                        "schema": {
                            "additionalProperties": false,
                            "description": "Standard Lunora error envelope.",
                            "properties": {
                                "error": {
                                    "additionalProperties": false,
                                    "properties": {
                                        "code": {
                                            "description": "Machine-readable error code. Clients switch on this value.",
                                            "enum": [
                                                "BAD_REQUEST",
                                                "CONFLICT",
                                                "COUNT_RLS_UNSUPPORTED",
                                                "FORBIDDEN",
                                                "FUNCTION_NOT_FOUND",
                                                "INTERNAL",
                                                "INTERNAL_SERVER_ERROR",
                                                "METHOD_NOT_ALLOWED",
                                                "NOT_FOUND",
                                                "NOT_IMPLEMENTED",
                                                "PAYLOAD_TOO_LARGE",
                                                "TOO_MANY_REQUESTS",
                                                "UNAUTHORIZED",
                                                "UNPROCESSABLE",
                                                "VALIDATION_ERROR"
                                            ],
                                            "type": "string"
                                        },
                                        "message": {
                                            "description": "Human-readable error message (never echoes internal details).",
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "code",
                                        "message"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "error"
                            ],
                            "type": "object"
                        }
                    }
                },
                "description": "A Lunora error response. The HTTP status reflects the error code (e.g. BAD_REQUEST→400, UNAUTHORIZED→401, FORBIDDEN→403, NOT_FOUND→404)."
            }
        }
    },
    "info": {
        "description": "Auto-generated from @lunora/values-typed functions by @lunora/codegen. Do not edit — run `lunora codegen` to regenerate.",
        "title": "Lunora API",
        "version": "1.8.0"
    },
    "openapi": "3.1.0",
    "paths": {},
    "tags": []
};
