// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

export const openApiSpec: Record<string, unknown> = {
    "components": {
        "responses": {
            "LunoraError": {
                "content": {
                    "application/json": {
                        "schema": {
                            "additionalProperties": false,
                            "description": "Standard Lunora error envelope.",
                            "properties": {
                                "error": {
                                    "additionalProperties": false,
                                    "properties": {
                                        "code": {
                                            "description": "Machine-readable error code. Clients switch on this value.",
                                            "enum": [
                                                "BAD_REQUEST",
                                                "CONFLICT",
                                                "COUNT_RLS_UNSUPPORTED",
                                                "FORBIDDEN",
                                                "FUNCTION_NOT_FOUND",
                                                "INTERNAL",
                                                "INTERNAL_SERVER_ERROR",
                                                "METHOD_NOT_ALLOWED",
                                                "NOT_FOUND",
                                                "NOT_IMPLEMENTED",
                                                "PAYLOAD_TOO_LARGE",
                                                "TOO_MANY_REQUESTS",
                                                "UNAUTHORIZED",
                                                "UNPROCESSABLE",
                                                "VALIDATION_ERROR"
                                            ],
                                            "type": "string"
                                        },
                                        "message": {
                                            "description": "Human-readable error message (never echoes internal details).",
                                            "type": "string"
                                        }
                                    },
                                    "required": [
                                        "code",
                                        "message"
                                    ],
                                    "type": "object"
                                }
                            },
                            "required": [
                                "error"
                            ],
                            "type": "object"
                        }
                    }
                },
                "description": "A Lunora error response. The HTTP status reflects the error code (e.g. BAD_REQUEST→400, UNAUTHORIZED→401, FORBIDDEN→403, NOT_FOUND→404)."
            }
        }
    },
    "info": {
        "description": "Auto-generated from @lunora/values-typed functions by @lunora/codegen. Do not edit — run `lunora codegen` to regenerate.",
        "title": "Lunora API",
        "version": "1.10.4"
    },
    "openapi": "3.1.0",
    "paths": {
        "/_lunora/rpc#agent:fireAgentRun": {
            "post": {
                "description": "Invoke the `action` `agent:fireAgentRun` over the Lunora RPC envelope (POST /_lunora/rpc).",
                "operationId": "agent:fireAgentRun",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "additionalProperties": false,
                                "properties": {
                                    "args": {
                                        "additionalProperties": false,
                                        "properties": {
                                            "userId": {
                                                "type": "string"
                                            },
                                            "questionNodeId": {
                                                "type": "string"
                                            }
                                        },
                                        "required": [
                                            "userId",
                                            "questionNodeId"
                                        ],
                                        "type": "object"
                                    },
                                    "functionPath": {
                                        "const": "agent:fireAgentRun",
                                        "type": "string"
                                    },
                                    "shardKey": {
                                        "description": "Optional shard key; omitted routes to the default shard.",
                                        "type": "string"
                                    }
                                },
                                "required": [
                                    "functionPath"
                                ],
                                "type": "object"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "description": "RPC result. The shape is TS-inferred from the function's return type; best-effort — any JSON."
                                }
                            }
                        },
                        "description": "Successful RPC result (TypeScript-inferred return shape, documented best-effort)."
                    },
                    "default": {
                        "$ref": "#/components/responses/LunoraError"
                    }
                },
                "summary": "action: agent:fireAgentRun",
                "tags": [
                    "agent"
                ],
                "x-lunora-function-kind": "action"
            }
        }
    },
    "tags": [
        {
            "description": "Operations declared in `lunora/agent`.",
            "name": "agent"
        }
    ]
};
