// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { createPolicyDsl, defineMutator as defineMutatorBase, initLunora, v as vBase } from "lunorash/server";
import type {
    ActionBuilder,
    ActionCtx as ActionCtxBase,
    ColumnValidator,
    DatabaseReader,
    DatabaseWriter,
    EmptyArgs,
    InternalActionBuilder,
    InternalMutationBuilder,
    InternalQueryBuilder,
    MutationBuilder,
    MutationCtx as MutationCtxBase,
    MutationStorage,
    MutatorDefinition,
    QueryBuilder,
    QueryCtx as QueryCtxBase,
    ReadOnlyStorage,
    RegisteredMutator,
    Storage as StorageBase,
    TableReader,
    Validator,
} from "lunorash/server";

import type {
    DatabaseReaderFacade as DatabaseReaderFacadeOf,
    DatabaseWriterFacade as DatabaseWriterFacadeOf,
    LoadWith as LoadWithOf,
    TableReaderFacade as TableReaderFacadeOf,
    TableWriterFacade as TableWriterFacadeOf,
    WithArg as WithArgOf,
} from "lunorash/server/data-model";

export type {
    AggregateOp,
    GroupByEntry,
    OrderBy,
    QueryArgs,
    QueryPage,
    RankPage,
    RankResult,
    RestrictableQueryOptions,
    RestrictableQueryOptionsOf,
    SearchFilterBuilder,
    SearchReader,
    TableAggregateOptions,
    TableAggregateOptionsOf,
    TableGroupByOptions,
    TableGroupByOptionsOf,
    TableRankOptions,
    TableRankPageOptions,
    Where,
    WhereOf,
    WhereOperators,
} from "lunorash/server/data-model";

import type { DataModel, Doc, GeoIndexNamesByTable, Id as IdOfTable, IndexNamesByTable, Insert, InsertModel, RankIndexNamesByTable, Relations, SearchIndexNamesByTable, TableName } from "./dataModel.js";

export type { AppTableName, DataModel, Doc, Id, TableName } from "./dataModel.js";

/**
 * The query-DSL bindings: `@lunora/server/data-model`'s generics parameterized
 * over this project's `DataModel` / `InsertModel` / `Relations` / index maps.
 *
 * They live here rather than in `dataModel.ts` because they are the half that
 * needs the SERVER package. Keeping `dataModel.ts` free of it lets a sibling
 * package — a web app, another Worker — compile `api.ts` for its `Doc`/`Id`
 * types without installing a server dependency to do it.
 */

/** The `with` argument for table `T` — see `@lunora/server/data-model`. */
export type WithArg<T extends keyof DataModel> = WithArgOf<DataModel, Relations, T>;

/** `Doc<T>` narrowed to exactly the relations requested in the with-arg `W`. */
export type LoadWith<T extends keyof DataModel, W> = LoadWithOf<DataModel, Relations, T, W>;

/** Read-only typed table accessor exposed on `QueryCtx.db.<table>`. */
export type TableReaderFacade<T extends keyof DataModel> = TableReaderFacadeOf<DataModel, Relations, RankIndexNamesByTable, SearchIndexNamesByTable, T, GeoIndexNamesByTable>;

/** Read-write typed table accessor exposed on `MutationCtx.db.<table>` / `ActionCtx.db.<table>`. */
export type TableWriterFacade<T extends keyof DataModel> = TableWriterFacadeOf<DataModel, InsertModel, Relations, RankIndexNamesByTable, SearchIndexNamesByTable, T, GeoIndexNamesByTable>;

/** Per-table read facade — `ctx.db.<table>` on a `QueryCtx`. */
export type DatabaseReaderFacade = DatabaseReaderFacadeOf<DataModel, Relations, RankIndexNamesByTable, SearchIndexNamesByTable, GeoIndexNamesByTable>;

/** Per-table read-write facade — `ctx.db.<table>` on a `MutationCtx` / `ActionCtx`. */
export type DatabaseWriterFacade = DatabaseWriterFacadeOf<DataModel, InsertModel, Relations, RankIndexNamesByTable, SearchIndexNamesByTable, GeoIndexNamesByTable>;

/** Insert builder returned by `ctx.orm.insert(table)`. */
export interface OrmInsertBuilder<T extends keyof DataModel> {
    values: (values: Insert<T>) => Promise<IdOfTable<T>>;
}

/** Replace builder returned by `ctx.orm.replace(table, id)` — swaps the whole document. */
export interface OrmReplaceBuilder<T extends keyof DataModel> {
    with: (values: Insert<T>) => Promise<void>;
}

/** Update builder returned by `ctx.orm.update(table, id)` — patches the named fields. */
export interface OrmUpdateBuilder<T extends keyof DataModel> {
    set: (values: Partial<Insert<T>>) => Promise<void>;
}

/** Read-only ORM surface — `ctx.orm` on a `QueryCtx`. Mirrors `ctx.db` reads under a kitcn-style `query` namespace. */
export interface OrmReader {
    query: DatabaseReaderFacade;
}

/** Read-write ORM surface — `ctx.orm` on a `MutationCtx` / `ActionCtx`. Writes are addressed by id, like `ctx.db`. */
export interface OrmWriter extends OrmReader {
    delete: <T extends keyof DataModel>(table: T, id: IdOfTable<T>) => Promise<void>;
    insert: <T extends keyof DataModel>(table: T) => OrmInsertBuilder<T>;
    replace: <T extends keyof DataModel>(table: T, id: IdOfTable<T>) => OrmReplaceBuilder<T>;
    update: <T extends keyof DataModel>(table: T, id: IdOfTable<T>) => OrmUpdateBuilder<T>;
}

/** Storage buckets this schema declares (`v.storage("name")`), narrowing `ctx.storage.bucket(name)`. */
export type StorageBucketName = "default";

/**
 * This project's Cloudflare bindings, as far as codegen can discover them from
 * `lunora/` source — the container/workflow Durable Object namespaces and the
 * conventional Workers AI binding. Bindings the config layer reconciles from
 * user-named wrangler config (R2/KV/D1/`services`/queues/…) aren't statically
 * visible here, so the open index signature keeps them reachable (cast at the
 * use site). Service bindings (`env.<SERVICE>.fetch(...)` / RPC stubs) live
 * under this signature too — Lunora can't type a third-party worker's RPC
 * surface, so treat them as `Fetcher`/`Service<unknown>` and cast.
 */
export interface CloudflareBindings {
    readonly [binding: string]: unknown;
}

/** Alias for {@link CloudflareBindings} — the typed shape of `env`. */
export type Env = CloudflareBindings;

/**
 * Project-typed contexts. The base contexts from `@lunora/server` are
 * untyped against the schema; here `db` is widened to the generated per-table
 * facade (`ctx.db.<table>.findMany(...)`) while keeping the legacy structural
 * `db.get`/`db.query` surface for back-compat, and `storage` is narrowed so
 * `ctx.storage.bucket(name)` autocompletes the declared buckets.
 */
/**
 * The Convex-style fluent reader `ctx.db.query(table)`, bound to this schema:
 * a table-name literal narrows the row type, so `.collect()` / `.first()` /
 * `.take()` (and the `.withIndex()` / `.filter()` / `.order()` chain) resolve
 * as `Doc<table>` with no `as unknown as Doc<...>` casts. The per-table accessor
 * `ctx.db.<table>` stays available alongside it via the facade.
 *
 * Intersected with the wide `(string) => TableReader` signature so the bound
 * `ctx.db` is still structurally assignable to schema-agnostic consumers that
 * call `db.query(someString)` (e.g. `@lunora/ratelimit`'s `createDbStore`).
 *
 * The three index-name unions are what make `.withIndex("by_TYPO")` a compile
 * error: each resolves to the table's declared names, or `never` when it
 * declares none of that kind. Without them a renamed or dropped index left
 * every call site typechecking, and the query either threw at runtime or
 * degraded silently to a full table scan.
 */
type TypedTableQuery = (<T extends TableName>(
    table: T,
) => TableReader<Doc<T>, IndexNamesByTable[T], SearchIndexNamesByTable[T], GeoIndexNamesByTable[T]>) &
    ((table: string) => TableReader);

/**
 * The point read `ctx.db.get(id)`, bound to this schema: an `Id<"table">`
 * carries its table name, so the resolved document is typed `Doc<table>` (or
 * `null` when absent) with no `as Doc<...>` cast. Mirrors {@link TypedTableQuery}.
 */
type TypedTableGet = <T extends TableName>(id: IdOfTable<T>) => Promise<Doc<T> | null>;

/**
 * Resolves the `asId` table argument: a literal in {@link TableName} passes through, a
 * genuinely-wide `string` (a computed name) passes through, and any OTHER literal
 * collapses to `never` so it fails to typecheck.
 *
 * The `string extends T` arm is what distinguishes "the caller passed a computed
 * string" from "the caller passed a misspelled literal" — only the wide `string` type
 * is a supertype of `string`.
 */
type AsIdTable<T extends string> = T extends TableName ? T : string extends T ? T : never;

/**
 * The id parse boundary `ctx.db.asId(table, id)`, bound to this schema: a misspelled
 * table literal is a compile error rather than a call that hands back a confidently-
 * branded id for a table that does not exist. Mirrors {@link TypedTableQuery} /
 * {@link TypedTableGet}.
 *
 * Deliberately NOT an intersection with a wide `(string, string) => string` overload:
 * overload resolution would fall through to it for a bad literal, silently restoring
 * the very typo hole this narrowing exists to close. {@link AsIdTable} instead keeps a
 * computed table name working — and keeps `ctx.db` structurally assignable to
 * schema-agnostic consumers — without accepting an invalid literal.
 */
type TypedAsId = <T extends string>(tableName: AsIdTable<T>, id: string) => IdOfTable<T & TableName>;

export interface QueryCtx extends Omit<QueryCtxBase, "db" | "storage"> {
    readonly db: Omit<DatabaseReader, "asId" | "query" | "get"> & DatabaseReaderFacade & { asId: TypedAsId; query: TypedTableQuery; get: TypedTableGet };
    readonly orm: OrmReader;
    readonly storage: ReadOnlyStorage<StorageBucketName>;
}

export interface MutationCtx extends Omit<MutationCtxBase, "db" | "storage"> {
    readonly db: Omit<DatabaseWriter, "asId" | "query" | "get"> & DatabaseWriterFacade & { asId: TypedAsId; query: TypedTableQuery; get: TypedTableGet };
    readonly orm: OrmWriter;
    readonly storage: MutationStorage<StorageBucketName>;
}

export interface ActionCtx extends Omit<ActionCtxBase, "db" | "storage"> {
    readonly db: Omit<DatabaseWriter, "asId" | "query" | "get"> & DatabaseWriterFacade & { asId: TypedAsId; query: TypedTableQuery; get: TypedTableGet };
    readonly orm: OrmWriter;
    readonly storage: StorageBase<StorageBucketName>;
}

/**
 * Procedure builders bound to this project's typed contexts. Chain
 * `.input({...})` to declare args, `.use(middleware)` for rate limiting / RLS /
 * masking (each middleware may refine `ctx`), then the terminal
 * `.query()` / `.mutation()` / `.action()` with a `({ ctx, args }) => ...`
 * handler. `.output(validator)` and (queries) `.stream()` are also available.
 */
const lunoraBuilders = initLunora.dataModel<DataModel>().create();

/** `query` builder bound to this project's typed {@link QueryCtx}. */
export const query = lunoraBuilders.query as unknown as QueryBuilder<QueryCtx, EmptyArgs>;

/** `mutation` builder bound to this project's typed {@link MutationCtx}. */
export const mutation = lunoraBuilders.mutation as unknown as MutationBuilder<MutationCtx, EmptyArgs>;

/** `action` builder bound to this project's typed {@link ActionCtx}. */
export const action = lunoraBuilders.action as unknown as ActionBuilder<ActionCtx, EmptyArgs>;

/** `internalQuery` builder bound to this project's typed {@link QueryCtx} — never exposed on `api`. */
export const internalQuery = lunoraBuilders.internalQuery as unknown as InternalQueryBuilder<QueryCtx, EmptyArgs>;

/** `internalMutation` builder bound to this project's typed {@link MutationCtx} — never exposed on `api`. */
export const internalMutation = lunoraBuilders.internalMutation as unknown as InternalMutationBuilder<MutationCtx, EmptyArgs>;

/** `internalAction` builder bound to this project's typed {@link ActionCtx} — never exposed on `api`. */
export const internalAction = lunoraBuilders.internalAction as unknown as InternalActionBuilder<ActionCtx, EmptyArgs>;

/**
 * `defineMutator` bound to this project's typed {@link MutationCtx} — declare
 * custom mutators (`lunora/mutators.ts`) with it instead of importing from
 * `lunorash/server`, and the authoritative `server` impl's `ctx` carries the
 * schema-typed `ctx.db` (`ctx.db.query("nodes")` resolves `Doc<"nodes">`,
 * `ctx.db.patch(id, …)` takes an `Id<"nodes">`) with no hand-written ctx type and
 * no `as unknown as` cast. Runtime-identical to the package export; only the
 * context type narrows, so discovery finds a mutator authored either way.
 * @example
 * export const setText = defineMutator({
 *     args: { id: v.id("nodes"), text: v.string() },
 *     server: async (ctx, args) => { await ctx.db.patch(args.id, { text: args.text }); },
 * });
 */
export const defineMutator = defineMutatorBase as unknown as <Args extends Record<string, Validator> = Record<string, Validator>, ClientTx = unknown, R = unknown>(
    definition: MutatorDefinition<Args, MutationCtx, ClientTx, R>,
) => RegisteredMutator<Args, MutationCtx, ClientTx, R>;

/**
 * `definePolicy` bound to THIS schema's {@link DataModel} + {@link Relations}.
 * Import it from here (`./_generated/server`) instead of `@lunora/server` to get
 * a relation-aware RLS authoring surface: `table` autocompletes to a real table
 * name and the `when` predicate type-checks against the table's columns **and**
 * its declared relations — `{ author: { is: {...} } }`, `{ posts: { some: {...} } }`,
 * etc. (the `@lunora/do` pre-resolver resolves relation predicates on reads).
 * Runtime-identical to `@lunora/server`'s `definePolicy`; only the types narrow,
 * so the `rls()` chain discovers a policy authored either way the same.
 */
export const definePolicy = createPolicyDsl<DataModel, Relations>();

/**
 * The validator builder `v`, with `v.id(...)` constrained to THIS schema's
 * table names — so the argument autocompletes and returns a precise
 * `Id<"table">`. Identical to `@lunora/server`'s `v` at runtime; the only
 * difference is the tightened `id` type.
 *
 * Import `v` from here (`./_generated/server`) in your queries/mutations/actions
 * to get table-name autocomplete. `lunora/schema.ts` can't use it — it is the
 * file that defines the table names, so they aren't known yet there; pass the
 * names as string literals and the generated `Id<"table">` types still catch a
 * typo wherever the id is used.
 */
export const v = vBase as unknown as Omit<typeof vBase, "id"> & {
    id: <T extends TableName>(table: T) => ColumnValidator<IdOfTable<T>, IdOfTable<T>>;
};
