// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import { createPolicyDsl, initLunora, v as vBase } from "lunorash/server";
import type {
    ActionBuilder,
    ActionCtx as ActionCtxBase,
    ColumnValidator,
    DatabaseReader,
    DatabaseWriter,
    EmptyArgs,
    InternalActionBuilder,
    InternalMutationBuilder,
    InternalQueryBuilder,
    MutationBuilder,
    MutationCtx as MutationCtxBase,
    QueryBuilder,
    QueryCtx as QueryCtxBase,
    ReadOnlyStorage,
    Storage as StorageBase,
    TableReader,
} from "lunorash/server";

import type { DataModel, DatabaseReaderFacade, DatabaseWriterFacade, Doc, Id as IdOfTable, OrmReader, OrmWriter, Relations, TableName } from "./dataModel.js";

export type { DataModel, Doc, Id, TableName } from "./dataModel.js";

/** Storage buckets this schema declares (`v.storage("name")`), narrowing `ctx.storage.bucket(name)`. */
export type StorageBucketName = "default";

/**
 * This project's Cloudflare bindings, as far as codegen can discover them from
 * `lunora/` source — the container/workflow Durable Object namespaces and the
 * conventional Workers AI binding. Bindings the config layer reconciles from
 * user-named wrangler config (R2/KV/D1/`services`/queues/…) aren't statically
 * visible here, so the open index signature keeps them reachable (cast at the
 * use site). Service bindings (`env.<SERVICE>.fetch(...)` / RPC stubs) live
 * under this signature too — Lunora can't type a third-party worker's RPC
 * surface, so treat them as `Fetcher`/`Service<unknown>` and cast.
 */
export interface CloudflareBindings {
    readonly [binding: string]: unknown;
}

/** Alias for {@link CloudflareBindings} — the typed shape of `env`. */
export type Env = CloudflareBindings;

/**
 * Project-typed contexts. The base contexts from `@lunora/server` are
 * untyped against the schema; here `db` is widened to the generated per-table
 * facade (`ctx.db.<table>.findMany(...)`) while keeping the legacy structural
 * `db.get`/`db.query` surface for back-compat, and `storage` is narrowed so
 * `ctx.storage.bucket(name)` autocompletes the declared buckets.
 */
/**
 * The Convex-style fluent reader `ctx.db.query(table)`, bound to this schema:
 * a table-name literal narrows the row type, so `.collect()` / `.first()` /
 * `.take()` (and the `.withIndex()` / `.filter()` / `.order()` chain) resolve
 * as `Doc<table>` with no `as unknown as Doc<...>` casts. The per-table accessor
 * `ctx.db.<table>` stays available alongside it via the facade.
 *
 * Intersected with the wide `(string) => TableReader` signature so the bound
 * `ctx.db` is still structurally assignable to schema-agnostic consumers that
 * call `db.query(someString)` (e.g. `@lunora/ratelimit`'s `createDbStore`).
 */
type TypedTableQuery = (<T extends TableName>(table: T) => TableReader<Doc<T>>) & ((table: string) => TableReader);

/**
 * The point read `ctx.db.get(id)`, bound to this schema: an `Id<"table">`
 * carries its table name, so the resolved document is typed `Doc<table>` (or
 * `null` when absent) with no `as Doc<...>` cast. Mirrors {@link TypedTableQuery}.
 */
type TypedTableGet = <T extends TableName>(id: IdOfTable<T>) => Promise<Doc<T> | null>;

export interface QueryCtx extends Omit<QueryCtxBase, "db" | "storage"> {
    readonly db: Omit<DatabaseReader, "query" | "get"> & DatabaseReaderFacade & { query: TypedTableQuery; get: TypedTableGet };
    readonly orm: OrmReader;
    readonly storage: ReadOnlyStorage<StorageBucketName>;
}

export interface MutationCtx extends Omit<MutationCtxBase, "db" | "storage"> {
    readonly db: Omit<DatabaseWriter, "query" | "get"> & DatabaseWriterFacade & { query: TypedTableQuery; get: TypedTableGet };
    readonly orm: OrmWriter;
    readonly storage: ReadOnlyStorage<StorageBucketName>;
}

export interface ActionCtx extends Omit<ActionCtxBase, "db" | "storage"> {
    readonly db: Omit<DatabaseWriter, "query" | "get"> & DatabaseWriterFacade & { query: TypedTableQuery; get: TypedTableGet };
    readonly orm: OrmWriter;
    readonly storage: StorageBase<StorageBucketName>;
}

/**
 * Procedure builders bound to this project's typed contexts. Chain
 * `.input({...})` to declare args, `.use(middleware)` for rate limiting / RLS /
 * masking (each middleware may refine `ctx`), then the terminal
 * `.query()` / `.mutation()` / `.action()` with a `({ ctx, args }) => ...`
 * handler. `.output(validator)` and (queries) `.stream()` are also available.
 */
const lunoraBuilders = initLunora.dataModel<DataModel>().create();

/** `query` builder bound to this project's typed {@link QueryCtx}. */
export const query = lunoraBuilders.query as unknown as QueryBuilder<QueryCtx, EmptyArgs>;

/** `mutation` builder bound to this project's typed {@link MutationCtx}. */
export const mutation = lunoraBuilders.mutation as unknown as MutationBuilder<MutationCtx, EmptyArgs>;

/** `action` builder bound to this project's typed {@link ActionCtx}. */
export const action = lunoraBuilders.action as unknown as ActionBuilder<ActionCtx, EmptyArgs>;

/** `internalQuery` builder bound to this project's typed {@link QueryCtx} — never exposed on `api`. */
export const internalQuery = lunoraBuilders.internalQuery as unknown as InternalQueryBuilder<QueryCtx, EmptyArgs>;

/** `internalMutation` builder bound to this project's typed {@link MutationCtx} — never exposed on `api`. */
export const internalMutation = lunoraBuilders.internalMutation as unknown as InternalMutationBuilder<MutationCtx, EmptyArgs>;

/** `internalAction` builder bound to this project's typed {@link ActionCtx} — never exposed on `api`. */
export const internalAction = lunoraBuilders.internalAction as unknown as InternalActionBuilder<ActionCtx, EmptyArgs>;

/**
 * `definePolicy` bound to THIS schema's {@link DataModel} + {@link Relations}.
 * Import it from here (`./_generated/server`) instead of `@lunora/server` to get
 * a relation-aware RLS authoring surface: `table` autocompletes to a real table
 * name and the `when` predicate type-checks against the table's columns **and**
 * its declared relations — `{ author: { is: {...} } }`, `{ posts: { some: {...} } }`,
 * etc. (the `@lunora/do` pre-resolver resolves relation predicates on reads).
 * Runtime-identical to `@lunora/server`'s `definePolicy`; only the types narrow,
 * so the `rls()` chain discovers a policy authored either way the same.
 */
export const definePolicy = createPolicyDsl<DataModel, Relations>();

/**
 * The validator builder `v`, with `v.id(...)` constrained to THIS schema's
 * table names — so the argument autocompletes and returns a precise
 * `Id<"table">`. Identical to `@lunora/server`'s `v` at runtime; the only
 * difference is the tightened `id` type.
 *
 * Import `v` from here (`./_generated/server`) in your queries/mutations/actions
 * to get table-name autocomplete. `lunora/schema.ts` can't use it — it is the
 * file that defines the table names, so they aren't known yet there; pass the
 * names as string literals and the generated `Id<"table">` types still catch a
 * typo wherever the id is used.
 */
export const v = vBase as unknown as Omit<typeof vBase, "id"> & {
    id: <T extends TableName>(table: T) => ColumnValidator<IdOfTable<T>, IdOfTable<T>>;
};
