// GENERATED by @lunora/codegen — do not edit.
// Run `lunora codegen` to regenerate.

import type { AdvisoryFinding, DatabaseWriterLike, DataMigrationLike, LogSink, MaskPoliciesResult, MigrationRunResult, RunShardApplyCdcArgs, RunShardMigrationArgs, RlsPoliciesResult, RunShardRankBeforeArgs, RunShardRankPageArgs, RunShardWriteArgs, RunShardWriteResult, SchedulerLike, SchemaLike, ShardDOState, ShardRankPageResult, SqlExec, StorageRulesResult, StudioFeaturesResult, SystemReaderStorageLike, WhereInput } from "lunorash/do";
import { applyCdcChanges, assertShapeShardable, createShardCtxDb, runDataMigration, runShardMigrations, ShardDO as ShardDOBase } from "lunorash/do";
import { asBucketStorage, buildRlsReadRegistry, composeShapeReadWhere, createSecrets, LunoraError } from "lunorash/server";
import { bindOrm, bindTableFacade } from "lunorash/server";

import schema from "../schema.js";
import { LUNORA_FUNCTIONS, LUNORA_LIFECYCLE_HOOKS, LUNORA_MIGRATIONS, LUNORA_MUTATOR_PATHS, LUNORA_SHAPES } from "./functions.js";

type FunctionKind = "action" | "mutation" | "query";

interface FunctionReference {
    __lunoraRef: string;
}

/** Foreign-key columns per table (`v.id("target")` fields) for the data browser. */
const LUNORA_TABLE_REFS: Record<string, Record<string, string>> = {};

/** Declared indexes per table (secondary, search, geo, rank, vector) for the schema viewer. */
const LUNORA_TABLE_INDEXES: Record<string, Array<{ fields: string[]; name: string; type: "geo" | "index" | "rank" | "search" | "vector"; unique?: boolean }>> = {
    "nodes": [
        {
            "fields": [
                "parentId"
            ],
            "name": "by_parent",
            "type": "index"
        }
    ],
    "ratelimit_buckets": [
        {
            "fields": [
                "key"
            ],
            "name": "by_key",
            "type": "index"
        }
    ]
};

/** Columns per table (typed, with PK/FK markers) for the studio's schema diagram, served via `__lunora_admin__:describeTable`. */
const LUNORA_TABLE_COLUMNS: Record<string, Array<{ isStorage?: boolean; name: string; optional: boolean; pk?: boolean; ref?: string; type: string }>> = {
    "nodes": [
        {
            "name": "_id",
            "optional": false,
            "pk": true,
            "type": "id"
        },
        {
            "name": "_creationTime",
            "optional": false,
            "type": "number"
        },
        {
            "name": "parentId",
            "optional": false,
            "type": "string"
        },
        {
            "name": "prevSiblingId",
            "optional": false,
            "type": "string"
        },
        {
            "name": "text",
            "optional": false,
            "type": "string"
        },
        {
            "name": "isTask",
            "optional": false,
            "type": "boolean"
        },
        {
            "name": "completed",
            "optional": false,
            "type": "boolean"
        },
        {
            "name": "collapsed",
            "optional": false,
            "type": "boolean"
        },
        {
            "name": "bookmarkedAt",
            "optional": false,
            "type": "number"
        },
        {
            "name": "mirrorOf",
            "optional": false,
            "type": "string"
        },
        {
            "name": "createdAt",
            "optional": false,
            "type": "number"
        },
        {
            "name": "updatedAt",
            "optional": false,
            "type": "number"
        },
        {
            "name": "origin",
            "optional": false,
            "type": "string"
        },
        {
            "name": "kind",
            "optional": false,
            "type": "literal"
        },
        {
            "name": "userId",
            "optional": false,
            "type": "string"
        }
    ],
    "ratelimit_buckets": [
        {
            "name": "_id",
            "optional": false,
            "pk": true,
            "type": "id"
        },
        {
            "name": "_creationTime",
            "optional": false,
            "type": "number"
        },
        {
            "name": "key",
            "optional": false,
            "type": "string"
        },
        {
            "name": "value",
            "optional": false,
            "type": "number"
        },
        {
            "name": "ts",
            "optional": false,
            "type": "number"
        },
        {
            "name": "prev",
            "optional": true,
            "type": "number"
        }
    ]
};

/** Storage-key columns per table (`v.storage(...)` fields) for the file browser's records↔files join. */
const LUNORA_STORAGE_COLUMNS: Record<string, string[]> = {};

/** Declarative TTL policies (`.ttl(field, { after? })`) the DO alarm sweep auto-expires rows for. */
const LUNORA_TTL_SWEEPS: Array<{ after?: number; field: string; softDeleteField?: string; table: string }> = [];

/** Static schema advisories (computed by @lunora/advisor at codegen time) served via `__lunora_admin__:getAdvisories`. */
const LUNORA_ADVISORIES: AdvisoryFinding[] = [
    {
        "cacheKey": "table_without_insert:nodes",
        "categories": [
            "SCHEMA"
        ],
        "description": "No function inserts into this table via `ctx.db.insert(\"<table>\", …)`. It may be read-only by design (seeded by a migration, replicated, or written through a path the advisor can't see) — or it may be dead schema.",
        "detail": "No function calls `ctx.db.insert(\"nodes\", …)` — table \"nodes\" has no discovered insert path.",
        "facing": "INTERNAL",
        "level": "INFO",
        "metadata": {
            "table": "nodes"
        },
        "name": "table_without_insert",
        "remediation": "If the table should be writable, add a mutation that calls `ctx.db.insert(\"<table>\", …)`. If it is read-only or seeded elsewhere, this advisory can be ignored.",
        "title": "Table has no insert path"
    },
    {
        "cacheKey": "plaintext_secret_in_wrangler_vars:wrangler.jsonc:SENTRY_DSN",
        "categories": [
            "SECURITY"
        ],
        "description": "A plaintext secret is committed to `wrangler.jsonc`'s `vars` block. `vars` are cleartext — baked into the deployed Worker and checked into source control — so the secret leaks via the repo and the bundle, and rotating it needs a config edit plus a redeploy.",
        "detail": "The `vars` entry `SENTRY_DSN` in wrangler.jsonc holds a plaintext hex secret (http…(95 chars)). `vars` ship in cleartext to the deployed Worker and are committed to source control — move it to a Secrets Store binding or `wrangler secret put` and rotate the exposed value.",
        "facing": "INTERNAL",
        "level": "ERROR",
        "metadata": {
            "file": "wrangler.jsonc",
            "key": "SENTRY_DSN",
            "kind": "hex_secret",
            "preview": "http…(95 chars)"
        },
        "name": "plaintext_secret_in_wrangler_vars",
        "remediation": "Move the value out of `vars`: bind it through a Secrets Store (`ctx.secrets.get(<NAME>)`) or set it with `wrangler secret put <NAME>` and read it from `env.<NAME>`. Delete the `vars` entry and rotate the exposed value — assume it is already compromised. Public/publishable keys (name them `*_PUBLIC` / `*_PUBLISHABLE`) are exempt.",
        "title": "Plaintext secret in wrangler vars"
    }
];

/** Read-only RLS metadata (policies + roles discovered from `.use(rls(...))` chains) served via `__lunora_admin__:rlsPolicies` for the studio's RLS inspector. */
const LUNORA_RLS_METADATA: RlsPoliciesResult = {
    "policies": [],
    "roles": []
};

/** Read-only masking metadata (table + column + strategy discovered from `.use(mask(...))` chains) served via `__lunora_admin__:maskPolicies` for the studio's data-browser mask preview. */
const LUNORA_MASK_METADATA: MaskPoliciesResult = {
    "columns": []
};

/** Read-only storage access-rule metadata (discovered from `.use(storageRules(...))` chains) served via `__lunora_admin__:storageRules` for the studio's access-rules view. */
const LUNORA_STORAGE_RULES: StorageRulesResult = {
    "rules": []
};

/** Which optional package-backed features this app wires up (discovered from imports / `ctx.*` reads / schema signals) served via `__lunora_admin__:studioFeatures` so the studio hides nav pages whose package isn't enabled. */
const LUNORA_STUDIO_FEATURES: StudioFeaturesResult = {
    "analytics": false,
    "auth": false,
    "containers": false,
    "flags": false,
    "kv": false,
    "mail": false,
    "payments": false,
    "queues": false,
    "scheduler": false,
    "storage": false,
    "vectors": false,
    "workflows": false
};

/** Per-table RLS read policies (hoisted from `.use(rls(...))` chains) the shape resolver AND-merges into each `defineShape` predicate so partial replication honours read policies. */
const LUNORA_RLS_READ_REGISTRY = buildRlsReadRegistry(Object.values(LUNORA_FUNCTIONS));

export interface ShardDOConfig {
    /** Opt into change-data-capture: records a post-image to `__cdc_log` on every write (backs streaming export + replay-PITR). */
    cdc?: boolean;
    /** Optional telemetry sink. When supplied, each `ctx.log.*` call is forwarded to `sink.onLog`. Pass the SAME sink you give `createWorker({ observability })` (which drives `onRpc`) to route both RPC and log events. */
    observability?: (env: Record<string, unknown>) => LogSink | undefined;
    scheduler?: (env: Record<string, unknown>) => unknown;
    storage?: (env: Record<string, unknown>) => unknown;
}

const schedulerStub = {
    cancel: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
    runAfter: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
    runAt: async () => {
        throw new Error("ctx.scheduler: no scheduler configured. Pass `scheduler` to createShardDO().");
    },
};

const storageStub = {
    delete: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    download: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    getMetadata: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    getSignedUrl: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    getUrl: () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    list: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
    upload: async () => {
        throw new Error("ctx.storage: no storage configured. Pass `storage` to createShardDO().");
    },
};

// Bound in-process `ctx.run*` composition depth so a self- or cyclically-
// referencing call fails loudly with a clear error instead of overflowing the
// stack. Tracked across the awaited handler chain (one DO invocation is
// single-threaded), so the counter reflects true nesting depth.
const MAX_RUN_DEPTH = 32;
let runDepth = 0;

const dispatchRun = async (expected: FunctionKind, functionPath: string, args: Record<string, unknown>, ctx: unknown): Promise<unknown> => {
    const registered = LUNORA_FUNCTIONS[functionPath];

    if (!registered) {
        throw new Error(`unknown function: ${functionPath}`);
    }

    if (registered.kind !== expected) {
        throw new Error(`ctx.run${expected[0]!.toUpperCase()}${expected.slice(1)}: "${functionPath}" is registered as a ${registered.kind}, not a ${expected}`);
    }

    if (runDepth >= MAX_RUN_DEPTH) {
        throw new LunoraError("RUN_DEPTH_EXCEEDED", `ctx.run*: composition depth limit (${MAX_RUN_DEPTH}) exceeded — likely a cyclic runQuery/runMutation`);
    }

    runDepth += 1;

    try {
        return await registered.handler(ctx, args);
    } finally {
        runDepth -= 1;
    }
};

/**
 * Build the project's shard Durable Object. Export the result as `ShardDO`
 * from the worker entry so wrangler binds it by name.
 */
export const createShardDO = (config: ShardDOConfig = {}): new (state: ShardDOState, env: unknown) => ShardDOBase =>
    class extends ShardDOBase {
        private migrated = false;

        public override async handleRpc(functionPath: string, args: Record<string, unknown>): Promise<unknown> {
            const registered = LUNORA_FUNCTIONS[functionPath];

            // Internal functions are reachable server-side only: via `ctx.run*`
            // composition, or a trusted system dispatch (scheduler/cron, marked by
            // `isSystemDispatch()`). A client RPC never carries that flag, so its
            // internals stay not-found and never leak across the external boundary.
            if (!registered || (registered.visibility === "internal" && !this.isSystemDispatch())) {
                throw new LunoraError("FUNCTION_NOT_FOUND", `function not registered: ${functionPath}`);
            }

            this.ensureMigrated();

            const ctx = this.buildCtx({ functionPath });

            // A mutation's writes must commit all-or-nothing: wrap its dispatch in
            // the DO's BEGIN/COMMIT span so any throw (a validator, an RLS denial,
            // an OCC conflict, a failed row mid-`insertMany`/`patchMany`) rolls
            // back every write the mutation made. Queries are read-only and actions
            // do external I/O that can't be rolled back, so both dispatch directly.
            // `ctx.run*` composition runs inside this span (it never re-enters
            // handleRpc); runInTransaction's own guard rejects accidental nesting.
            //
            // The replay bookkeeping (idempotency dedup row + custom-mutator
            // watermark advance) commits INSIDE this span via
            // `commitMutationBookkeeping`, so the writes, the dedup row, and the
            // watermark are atomic — a crash can't leave the writes durable without
            // the replay guard.
            if (registered.kind === "mutation") {
                return this.runInTransaction(async () => {
                    const result = await registered.handler(ctx, args);

                    this.commitMutationBookkeeping(result);

                    return result;
                });
            }

            return registered.handler(ctx, args);
        }

        protected override async executeSubscription(functionPath: string, args: Record<string, unknown>, identity?: { identity?: Record<string, unknown>; userId?: string }): Promise<{ result: unknown; tables: Set<string> } | null> {
            const registered = LUNORA_FUNCTIONS[functionPath];

            if (!registered || registered.kind !== "query" || registered.visibility === "internal") {
                return null;
            }

            this.ensureMigrated();

            const tables = new Set<string>();
            // Identity is threaded EXPLICITLY from the (deferred/interleaved)
            // subscription caller — never read from the shared per-request field
            // here — so a concurrent RPC can't leak its identity into this re-run.
            const ctx = this.buildCtx({ functionPath, identity, onRead: (table) => tables.add(table) });
            const result = await registered.handler(ctx, args);

            return { result, tables };
        }

        protected override executeStream(functionPath: string, args: Record<string, unknown>): null | { iterator: (signal: AbortSignal) => AsyncIterable<unknown> } {
            const registered = LUNORA_FUNCTIONS[functionPath];

            if (!registered || registered.kind !== "stream" || registered.visibility === "internal") {
                return null;
            }

            this.ensureMigrated();

            return {
                iterator: (signal) => (registered.handler as (context: unknown, args: Record<string, unknown>, signal: AbortSignal) => AsyncIterable<unknown>)(this.buildCtx({ functionPath }), args, signal),
            };
        }

        protected override isCustomMutator(functionPath: string): boolean {
            return LUNORA_MUTATOR_PATHS.has(functionPath);
        }

        protected override resolveShape(name: string, args: Record<string, unknown>, identity?: { identity?: Record<string, unknown>; userId?: string }): { columns?: readonly string[]; effectiveWhere?: WhereInput; global?: boolean; table: string } | undefined {
            const shape = LUNORA_SHAPES[name];

            if (!shape) {
                return undefined;
            }

            this.ensureMigrated();

            // Trusted ctx from the socket's OWN verified identity — the client
            // supplies only the shape name + args; `compileWhere` validates the
            // args then runs the shape's `where(ctx, args)` under that identity,
            // so which rows replicate is a server decision (reads-as-permissions).
            const ctx = this.buildCtx({ functionPath: `__shape__:${name}`, identity });
            const shapeWhere = shape.compileWhere(ctx, args) as unknown as WhereInput;

            // AND-compose with the table's RLS read base-where. A shape runs no
            // procedure, so the `.use(rls(...))` middleware never fires; without
            // this merge its reads would bypass every read policy on the table
            // (rows the caller can't see would replicate). `composeShapeReadWhere`
            // evaluates the table's read policies under this same trusted ctx —
            // exactly the request-time path — and fails closed under a
            // `.rls("required")` schema for a non-`.public()`, policy-less table.
            const effectiveWhere = composeShapeReadWhere(LUNORA_RLS_READ_REGISTRY, {
                ctx,
                identity: identity?.identity ?? null,
                rlsRequired: (schema as unknown as { rlsMode?: string }).rlsMode === "required",
                roles: (ctx as { auth?: { roles?: readonly string[] } }).auth?.roles ?? [],
                shapeWhere,
                table: shape.table,
                tablePublic: (schema as unknown as { tables: Record<string, { isPublic?: boolean }> }).tables[shape.table]?.isPublic === true,
                userId: identity?.userId ?? null,
            });

            // A live shape pokes only from its OWN shard's op-log, so a `where()`
            // that joins to a `.shardBy()` table (rows in another DO) is rejected
            // here — the first point the compiled predicate + shard modes are both
            // known. Remedy: denormalize, or move the joined table to `.global()`.
            assertShapeShardable(effectiveWhere, schema as unknown as SchemaLike, shape.table);

            // A `.global()` table lives in D1 (no per-DO op-log): flag it so the
            // base serves it through the latency-tiered poll path (`readGlobalShapeRows`)
            // instead of the CDC poke path.
            const isGlobal = (schema as unknown as SchemaLike).tables[shape.table]?.shardMode?.kind === "global";

            return { columns: shape.columns, effectiveWhere, global: isGlobal, table: shape.table };
        }

        protected override lifecycleHookPaths(event: "connect" | "disconnect"): readonly string[] {
            return LUNORA_LIFECYCLE_HOOKS[event];
        }

        protected override tableRefs(table: string): Record<string, string> | undefined {
            return LUNORA_TABLE_REFS[table];
        }

        protected override tableIndexes(table: string): Array<{ fields: string[]; name: string; type: "geo" | "index" | "rank" | "search" | "vector"; unique?: boolean }> {
            return LUNORA_TABLE_INDEXES[table] ?? [];
        }

        protected override ttlSweeps(): ReadonlyArray<{ after?: number; field: string; softDeleteField?: string; table: string }> {
            return LUNORA_TTL_SWEEPS;
        }

        protected override tableColumns(table: string): Array<{ isStorage?: boolean; name: string; optional: boolean; pk?: boolean; ref?: string; type: string }> {
            return LUNORA_TABLE_COLUMNS[table] ?? [];
        }

        protected override storageColumns(): Record<string, string[]> {
            return LUNORA_STORAGE_COLUMNS;
        }

        protected override rlsMetadata(): RlsPoliciesResult {
            return LUNORA_RLS_METADATA;
        }

        protected override maskMetadata(): MaskPoliciesResult {
            return LUNORA_MASK_METADATA;
        }

        protected override storageRulesMetadata(): StorageRulesResult {
            return LUNORA_STORAGE_RULES;
        }

        protected override studioFeatures(): StudioFeaturesResult {
            return LUNORA_STUDIO_FEATURES;
        }

        protected override advisories(): AdvisoryFinding[] {
            return LUNORA_ADVISORIES;
        }

        protected override async runShardDataMigration(args: RunShardMigrationArgs): Promise<MigrationRunResult> {
            const migration = LUNORA_MIGRATIONS[args.id];

            if (!migration) {
                throw new LunoraError("MIGRATION_NOT_FOUND", `data migration "${args.id}" is not registered`, { status: 404 });
            }

            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            return runDataMigration({
                batchSize: args.batchSize,
                direction: args.direction,
                dryRun: args.dryRun,
                maxBatches: args.maxBatches,
                migration: migration as unknown as DataMigrationLike,
                // Flush after each batch so live migrationStatus subscribers see
                // progress mid-run (the base method records the reserved state
                // table the raw-SQL progress write is invisible to the tracker).
                onBatch: () => this.flushMigrationProgress(),
                sql: this.sql as SqlExec,
                writer,
            });
        }

        protected override async runShardWrite(args: RunShardWriteArgs): Promise<RunShardWriteResult> {
            const definition = (schema as unknown as SchemaLike).tables[args.table];

            if (!definition) {
                throw new LunoraError("UNKNOWN_TABLE", `unknown table: ${args.table}`, { status: 404 });
            }

            // `.global()` tables live in D1, not this DO's SQLite — editing them
            // here would corrupt nothing but would fail confusingly, so reject up
            // front with a clear code the studio can surface.
            if (definition.shardMode?.kind === "global") {
                throw new LunoraError("GLOBAL_TABLE_NOT_EDITABLE", `table "${args.table}" is global; edit it through D1, not the shard`, { status: 400 });
            }

            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            if (args.op === "insert") {
                const id = await writer.insert(args.table, args.doc ?? {});

                return { id, op: "insert" };
            }

            if (args.op === "delete") {
                await writer.delete(args.id ?? "");

                return { id: args.id ?? null, op: "delete" };
            }

            if (args.op === "replace") {
                await writer.replace(args.id ?? "", args.doc ?? {});

                return { id: args.id ?? null, op: "replace" };
            }

            await writer.patch(args.id ?? "", args.doc ?? {});

            return { id: args.id ?? null, op: "patch" };
        }

        protected override async deleteRowThroughWriter(table: string, id: string): Promise<void> {
            const definition = (schema as unknown as SchemaLike).tables[table];

            if (!definition) {
                throw new LunoraError("UNKNOWN_TABLE", `unknown table: ${table}`, { status: 404 });
            }

            // `.global()` tables live in D1, not this DO's SQLite — the same
            // guard `runShardWrite` applies to single-row edits.
            if (definition.shardMode?.kind === "global") {
                throw new LunoraError("GLOBAL_TABLE_NOT_EDITABLE", `table "${table}" is global; edit it through D1, not the shard`, { status: 400 });
            }

            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            // Routes through the writer (not raw SQL) so FTS / aggregate / rank
            // shadow tables stay in sync and `onDelete` cascades fire — the
            // bounded loop lives in the base `runShardBulkDelete`.
            await writer.delete(id);
        }

        protected override async runShardRankBefore(args: RunShardRankBeforeArgs): Promise<{ before: number; total: number }> {
            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            // `rankBefore` is optional on `DatabaseWriterLike` (the D1 twin omits it),
            // but the shard writer from `createShardCtxDb` always defines it.
            if (!writer.rankBefore) {
                throw new LunoraError("NOT_IMPLEMENTED", "rankBefore is unavailable on the shard writer", { status: 500 });
            }

            return writer.rankBefore(args.table, args.index, {
                partitionKey: args.partitionKey,
                rowId: args.rowId,
                sortValues: args.sortValues,
            });
        }

        protected override async runShardRankPage(args: RunShardRankPageArgs): Promise<ShardRankPageResult> {
            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            // `rankPageRows` is optional on `DatabaseWriterLike` (the D1 twin omits it),
            // but the shard writer from `createShardCtxDb` always defines it. The sort
            // directions live in the schema's rankIndex, so the shard reads them itself;
            // `args.directions` is only the coordinator's comparator hint and isn't forwarded.
            if (!writer.rankPageRows) {
                throw new LunoraError("NOT_IMPLEMENTED", "rankPage is unavailable on the shard writer", { status: 500 });
            }

            return writer.rankPageRows(args.table, args.index, {
                after: args.after,
                cursor: args.cursor,
                partitionKey: args.partitionKey,
                take: args.take,
            });
        }

        protected override async runShardApplyCdc(args: RunShardApplyCdcArgs): Promise<{ applied: number }> {
            this.ensureMigrated();

            const env = (this.env ?? {}) as Record<string, unknown>;
            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            const writer = createShardCtxDb({
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
            });

            await applyCdcChanges(writer, args.changes);

            return { applied: args.changes.length };
        }

        protected override ensureMigrated(): void {
            if (this.migrated) {
                return;
            }

            runShardMigrations(this.sql as SqlExec, schema as unknown as SchemaLike, { cdc: config.cdc ?? false });
            this.migrated = true;
        }

        private buildCtx(options: { functionPath?: string; identity?: { identity?: Record<string, unknown>; userId?: string }; onRead?: (table: string) => void } = {}): unknown {
            const env = (this.env ?? {}) as Record<string, unknown>;
            // When the caller threads an explicit identity (subscription seed /
            // refresh — both run in deferred/interleaved contexts), use it by
            // value and NEVER read the shared per-request identity field, which a
            // concurrent RPC may have re-set. Otherwise (the synchronous RPC
            // dispatch path) fall back to the per-request fields as before.
            const userId = options.identity ? options.identity.userId : this.getCurrentUserId();
            const identity = options.identity ? options.identity.identity : this.getCurrentIdentity();

            const secrets = createSecrets(env);

            const scheduler = (config.scheduler?.(env) ?? schedulerStub) as SchedulerLike;
            // Build the storage adapter once and share it between `ctx.storage`
            // and `ctx.db.system._storage` so both read the same R2 binding. The
            // `storageStub` fallback satisfies SystemReaderStorageLike structurally
            // (its `list`/`getMetadata` throw the "no storage configured" error).
            const storage = asBucketStorage(config.storage?.(env) ?? storageStub) as unknown as SystemReaderStorageLike;
            const db: DatabaseWriterLike = createShardCtxDb({
                auth: { identity: identity ?? null, userId: userId ?? null },
                broadcast: (delta) => {
                    this.recordChangedTable(delta.table);
                },
                cdc: config.cdc ?? false,
                enforceRls: true,
                onIndexUse: this.getCtxDbIndexUseHook(),
                onRead: options.onRead ?? this.getCtxDbReadHook(),
                scheduler,
                schema: schema as unknown as SchemaLike,
                sql: this.sql as SqlExec,
                storage,
            });

            const facade = db as unknown as Record<string, ReturnType<typeof bindTableFacade>>;
            facade["nodes"] = bindTableFacade(db, "nodes");
            facade["ratelimit_buckets"] = bindTableFacade(db, "ratelimit_buckets");

            // `ctx.log`: the DO base builds the attributed logger (structured
            // fields + `.with(...)` child + trace correlation) and routes each call
            // to the optional `observability` sink. It also buffers the line (studio
            // Logs panel) and emits a structured console event the dev-server formats.
            const observability = config.observability?.(env);
            const logFunctionPath = options.functionPath ?? "";
            const log = this.makeLogger(logFunctionPath, observability);

            // `ctx.trace` / `ctx.metrics`: spans and measurements to the same sink.
            // The trace anchor is threaded explicitly for the same reason `identity`
            // is — a deferred caller (a subscription re-run) must not inherit the
            // writing mutation's trace from the shared per-request field.
            const trace = this.makeTracer(logFunctionPath, observability, options.identity ? undefined : this.getCurrentTrace());
            const metrics = this.makeMetrics(logFunctionPath, observability);

            // `ctx.now`: the wall-clock instant (epoch ms) this function began,
            // captured ONCE so the whole handler body sees a single stable value.
            // Query/mutation handlers must be deterministic (they may be re-run on
            // OCC retry / subscription re-eval), so they must read time through
            // `ctx.now` instead of `Date.now()` — the `nondeterministic_query_mutation`
            // advisor flags the latter. Actions may still use ambient `Date.now()`.
            const now = Date.now();

            const ctx: Record<string, unknown> = {
                auth: {
                    getIdentity: async () => identity ?? null,
                    userId: userId ?? null,
                },
                db,
                fetch: globalThis.fetch.bind(globalThis),
                ip: this.getCurrentIp(),
                log,
                metrics,
                now,
                orm: bindOrm(facade),
                scheduler,
                storage,
                trace,
                secrets,
            };

            ctx.runAction = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("action", reference.__lunoraRef, fnArgs, ctx);
            ctx.runMutation = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("mutation", reference.__lunoraRef, fnArgs, ctx);
            ctx.runQuery = (reference: FunctionReference, fnArgs: Record<string, unknown>) => dispatchRun("query", reference.__lunoraRef, fnArgs, ctx);

            return ctx;
        }
    };
