/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NodeIdRouteImport } from './routes/$nodeId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminWaitlistRouteImport } from './routes/admin.waitlist'

const NodeIdRoute = NodeIdRouteImport.update({
  id: '/$nodeId',
  path: '/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWaitlistRoute = AdminWaitlistRouteImport.update({
  id: '/admin/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$nodeId': typeof NodeIdRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$nodeId': typeof NodeIdRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$nodeId': typeof NodeIdRoute
  '/admin/waitlist': typeof AdminWaitlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$nodeId' | '/admin/waitlist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$nodeId' | '/admin/waitlist'
  id: '__root__' | '/' | '/$nodeId' | '/admin/waitlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NodeIdRoute: typeof NodeIdRoute
  AdminWaitlistRoute: typeof AdminWaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$nodeId': {
      id: '/$nodeId'
      path: '/$nodeId'
      fullPath: '/$nodeId'
      preLoaderRoute: typeof NodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/waitlist': {
      id: '/admin/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NodeIdRoute: NodeIdRoute,
  AdminWaitlistRoute: AdminWaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
