/**
 * The changelog's pure core (ADR 0046): parse archived changeset fragments into
 * the `Release[]` the app renders, and answer "how many did I miss".
 *
 * Dependency-free apart from `effect/Schema` on purpose. It is imported by THREE
 * consumers across two runtimes: the Vite plugin (`scripts/vite-plugin-changelog.ts`,
 * node, build time), the app (`changelog-data.ts`, browser), and `bun test`. No
 * fs, no DOM, no React — the same discipline as `wire-schema.ts`.
 *
 * The fragments are the source. `CHANGELOG.md` is generated by changesets for
 * the GitHub Release and is NEVER parsed back into app data — see the ADR.
 */

import { Schema } from "effect";

/** Semver bump levels, in disclosure order (see ADR 0046: MAJOR means "a reader
 *  has to do something"). Order is load-bearing — it's the render order. */
export const BUMPS = ["major", "minor", "patch"] as const;
export type Bump = (typeof BUMPS)[number];

const BumpSchema = Schema.Literals(BUMPS);

/** One line of a release: what changed, and how loudly. There is deliberately no
 *  `category` field — the bump type already is Changed/Added/Fixed (ADR 0046). */
export const ChangelogEntrySchema = Schema.Struct({
  bump: BumpSchema,
  summary: Schema.String,
});
export type ChangelogEntry = Schema.Schema.Type<typeof ChangelogEntrySchema>;

export const ReleaseSchema = Schema.Struct({
  version: Schema.String,
  /** Local calendar day, `YYYY-MM-DD`. */
  date: Schema.String,
  entries: Schema.Array(ChangelogEntrySchema),
});
export type Release = Schema.Schema.Type<typeof ReleaseSchema>;

/** The whole changelog, newest release first. Array order IS release order —
 *  there is no `seq` and no semver parser in the client bundle (ADR 0046). */
export const ChangelogSchema = Schema.Array(ReleaseSchema);

const decodeChangelog = Schema.decodeUnknownExit(ChangelogSchema);

/** What the build-time reader hands us: one archived release, fragments verbatim. */
export interface ReleaseInput {
  version: string;
  date: string;
  /** Raw fragment markdown, in stable (filename) order. */
  fragments: readonly string[];
}

const VERSION_PATTERN = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/** `---\n<frontmatter>\n---` at the head of a changeset fragment. The body may be
 *  empty (`changeset --empty`), which is how a PR declares "this isn't news". */
const FRONTMATTER_PATTERN =
  /^---[ \t]*\r?\n([\s\S]*?)\r?\n?---[ \t]*(?:\r?\n|$)/;

/** `"dotflowy": minor` — the package name is irrelevant here (single-package repo). */
const BUMP_LINE_PATTERN = /:[ \t]*(major|minor|patch)[ \t]*$/;

const rank: Record<Bump, number> = { major: 0, minor: 1, patch: 2 };

/**
 * Parse one changeset fragment.
 *
 * Three outcomes, and the difference between the last two is the whole point:
 * an entry, `null` for an intentionally-empty changeset (`changeset --empty`,
 * the escape hatch that satisfies CI on a `chore:` PR without inventing news),
 * or an `Error` for a fragment whose frontmatter says *something* that isn't a
 * bump. Silently swallowing the third as "empty" would drop a real disclosure.
 */
export function parseFragment(source: string): ChangelogEntry | null | Error {
  const match = FRONTMATTER_PATTERN.exec(source);
  if (!match) return new Error("fragment has no `---` frontmatter block");

  const lines = match[1]!
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
  if (lines.length === 0) return null;

  let bump: Bump | null = null;
  for (const line of lines) {
    const hit = BUMP_LINE_PATTERN.exec(line);
    if (hit) {
      bump = hit[1] as Bump;
      break;
    }
  }
  if (!bump) {
    return new Error(
      `fragment frontmatter declares no major|minor|patch bump: ${lines.join("; ")}`,
    );
  }

  const summary = source.slice(match[0].length).trim();
  if (!summary) return new Error(`${bump} fragment has an empty summary`);
  return { bump, summary };
}

/**
 * Assemble the archived releases into the app's data, newest first.
 *
 * Value-as-error (the repo's `bootstrapOutline` idiom): every failure is a build
 * failure with a message that names the offending file's release, because the
 * only caller is the Vite plugin and a malformed entry must fail the build, not
 * production (ADR 0046, same spine as ADR 0014).
 *
 * `inputs` arrive in CHRONOLOGICAL order (the manifest is appended to); the
 * result is reversed so `releases[0]` is the latest.
 */
export function buildReleases(
  inputs: readonly ReleaseInput[],
): Release[] | Error {
  const seen = new Set<string>();
  const releases: Release[] = [];

  for (const input of inputs) {
    const { version, date } = input;
    if (!VERSION_PATTERN.test(version)) {
      return new Error(`"${version}" is not a semver version`);
    }
    if (seen.has(version)) return new Error(`duplicate release ${version}`);
    seen.add(version);
    if (!DATE_PATTERN.test(date)) {
      return new Error(
        `release ${version} has a non-YYYY-MM-DD date "${date}"`,
      );
    }

    const entries: ChangelogEntry[] = [];
    for (const fragment of input.fragments) {
      const parsed = parseFragment(fragment);
      if (parsed instanceof Error) {
        return new Error(`release ${version}: ${parsed.message}`);
      }
      if (parsed) entries.push(parsed);
    }
    if (entries.length === 0) {
      return new Error(`release ${version} has no entries`);
    }
    // Stable sort: major first, then the fragments' own (filename) order.
    entries.sort((a, b) => rank[a.bump] - rank[b.bump]);
    releases.push({ version, date, entries });
  }

  releases.reverse();

  const exit = decodeChangelog(releases);
  if (exit._tag === "Failure") {
    return new Error(`changelog failed schema validation: ${exit.cause}`);
  }
  return releases;
}

/**
 * How many releases the reader hasn't seen. The cursor is a VERSION, so this is
 * a `findIndex` — no integer compare, no semver parsing.
 *
 * Both "unknown version" (`-1`, e.g. a cursor written by a build whose archive
 * has since been rewritten) and "already latest" (`0`) mean **nothing to show**.
 * A badge that cries wolf is worse than no badge (ADR 0046), so the ambiguous
 * case stays quiet.
 *
 * A `null` cursor is "not loaded / no row" and is likewise 0 — the caller seeds
 * it silently. Never treat it as "unseen everything."
 */
export function unseenCount(
  releases: readonly Release[],
  lastSeenVersion: string | null,
): number {
  if (lastSeenVersion == null) return 0;
  const i = releases.findIndex((r) => r.version === lastSeenVersion);
  return i <= 0 ? 0 : i;
}

/** Does any of these releases demand action from the reader? Drives the dialog's
 *  "Breaking" callout — derived from the bump type already in the data, no new
 *  state (ADR 0046). */
export function hasBreaking(releases: readonly Release[]): boolean {
  return releases.some((r) => r.entries.some((e) => e.bump === "major"));
}
